### ISSUE TITLE
An Exception occurred : Failed to parse: http:\\issues.apache.org\jira\projects\OAK

### ISSUE THREAD

**Issue by DebuggerIssuesReport** [BGU-AiDnD/Debugger#1037]
An Exception occurred while running Debugger:

command line is wrapper.py antConf.txt learn

Traceback (most recent call last):
  File "C:\temp\Debugger\learner\utilsConf.py", line 386, in f
    ans = func(*args, **kwargs)
  File "C:\temp\Debugger\learner\wekaMethods\issuesExtract\jira_import.py", line 55, in jiraIssues
    jiraE = jira.JIRA(url)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\client.py", line 525, in __init__
    si = self.server_info()
  File "C:\Users\rotem\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\client.py", line 2425, in server_info
    j = self._get_json('serverInfo')
  File "C:\Users\rotem\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\client.py", line 2992, in _get_json
    r = self._session.get(url, params=params)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\resilientsession.py", line 151, in get
    return self.__verb('GET', url, **kwargs)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\resilientsession.py", line 125, in __verb
    response = method(url, timeout=self.timeout, **kwargs)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\requests\sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\requests\sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\rotem\Anaconda2\lib\site-packages\requests\models.py", line 309, in prepare
    self.prepare_url(url, params)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\requests\models.py", line 377, in prepare_url
    raise InvalidURL(*e.args)
InvalidURL: Failed to parse: http:\\issues.apache.org\jira\projects\OAK

**Comment by DebuggerIssuesReport** [comment]
Configuration is : 
('MethodsParsed', u'C:\\new_users\\tmp_1\\Jack\\out\\commitsFiles\\CheckStyle.txt')
('learning_dir', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\learning')
('full_configure_file', 'workingDir=C:\\new_users\\tmp_1\\Jack\\out\ngit=C:\\new_users\\tmp_1\\Jack\\rootGit\\jackrabbit-oak\nissue_tracker_product_name=OAK\nissue_tracker_url=http:\\\\issues.apache.org\\jira\\projects\\OAK\nissue_tracker=jira\nvers=(0.2.1,jackrabbit-oak-0.1,jackrabbit-oak-0.10,jackrabbit-oak-0.11,jackrabbit-oak-0.12,jackrabbit-oak-0.13)')
('docletPath', 'C:\\temp\\Debugger\\utils\\xml-doclet-1.0.4-jar-with-dependencies.jar')
('distribution_per_version_report', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\distribution_per_version_report.csv')
('experiments', u'C:\\new_users\\tmp_1\\Jack\\out\\experiments')
('sourceMonitorEXE', 'C:\\temp\\Debugger\\utils\\SourceMonitor.exe')
('checkStyle57', 'C:\\temp\\Debugger\\utils\\checkstyle-5.7-all.jar')
('distribution_per_majors_report', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\distribution_per_majors_report.csv')
('gitPath', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\rootGit\\jackrabbit-oak')
('prediction_files', {'Method': {'Most': 'prediction_Most_Method.csv', 'All': 'prediction_All_Method.csv'}, 'File': {'Most': 'prediction_Most_File.csv', 'All': 'prediction_All_File.csv'}})
('current_dir', 'C:\\temp\\Debugger\\learner')
('debugger_base_path', 'C:\\temp\\Debugger')
('paths', ['0.2.1\\repo', 'jackrabbit-oak-0.1\\repo', 'jackrabbit-oak-0.10\\repo', 'jackrabbit-oak-0.11\\repo', 'jackrabbit-oak-0.12\\repo', 'jackrabbit-oak-0.13\\repo'])
('versPath', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\vers')
('buggy_repo', <git.Repo "C:\new_users\tmp_1\Jack\rootGit\jackrabbit-oak\.git">)
('buggedType', 'File')
('markers_dir', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\markers')
('workingDir', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out')
('RemoveBat', 'C:\\temp\\Debugger\\utils\\../removeBat.bat')
('distribution_per_minors_report', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\distribution_per_minors_report.csv')
('caching_dir', 'C:\\temp\\Debugger\\Debugger_cache')
('all_but_one_dir', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\learning\\AllbutOne')
('confFile', 'antConf.txt')
('issue_tracker_product', 'OAK')
('db_dir', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\dbAdd')
('LocalGitPath', u'C:\\new_users\\tmp_1\\Jack\\out\\repo')
('changeFile', u'C:\\new_users\\tmp_1\\Jack\\out\\commitsFiles\\Ins_dels.txt')
('vers', ['0.2.1', 'jackrabbit-oak-0.1', 'jackrabbit-oak-0.10', 'jackrabbit-oak-0.11', 'jackrabbit-oak-0.12', 'jackrabbit-oak-0.13'])
('utilsPath', 'C:\\temp\\Debugger\\utils')
('checkStyle68', 'C:\\temp\\Debugger\\utils\\checkstyle-6.8-SNAPSHOT-all.jar')
('commits', [114212489, 162817295, 186530079, 43334606, 31593055, 36590177])
('methodsNamesXML', 'C:\\temp\\Debugger\\utils\\methodNameLines.xml')
('vers_dirs', ['0_2_1', 'jackrabbit_oak_0_1', 'jackrabbit_oak_0_10', 'jackrabbit_oak_0_11', 'jackrabbit_oak_0_12', 'jackrabbit_oak_0_13'])
('configuration_path', u'C:\\new_users\\tmp_1\\Jack\\out\\configuration')
('amir_tracer', 'C:\\temp\\Debugger\\utils\\uber-tracer-1.0.1-SNAPSHOT.jar')
('distribution_report', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\distribution_report.csv')
('weka_path', u'C:\\new_users\\tmp_1\\Jack\\out\\weka')
('granularity', 'Most')
('vers_paths', [u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\vers\\0_2_1', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\vers\\jackrabbit_oak_0_1', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\vers\\jackrabbit_oak_0_10', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\vers\\jackrabbit_oak_0_11', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\vers\\jackrabbit_oak_0_12', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\vers\\jackrabbit_oak_0_13'])
('configuration', <utilsConf.Configuration object at 0x0000000009829E48>)
('bugsPath', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\bugs.csv')
('issue_tracker', 'jira')
('remotes_urls', [u'https://github.com/apache/jackrabbit-oak'])
('repo', <git.Repo "C:\temp\Debugger\.git">)
('dates', ['2012-05-03 12:51:18', '2012-03-30 12:41:39', '2013-10-03 17:42:47', '2013-11-17 23:41:58', '2013-11-25 17:07:24', '2013-12-09 22:49:34'])
('renamed_mapping', {})
('versions', ['0.2.1', 'jackrabbit-oak-0.1', 'jackrabbit-oak-0.10', 'jackrabbit-oak-0.11', 'jackrabbit-oak-0.12', 'jackrabbit-oak-0.13'])
('wekaJar', 'C:\\temp\\Debugger\\utils\\weka.jar')
('DebuggerTests', u'C:\\new_users\\tmp_1\\Jack\\out\\DebuggerTests')
('distribution_per_micros_report', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\distribution_per_micros_report.csv')
('issue_tracker_url', 'http:\\\\issues.apache.org\\jira\\projects\\OAK')
('one_dir', u'\\\\?\\C:\\new_users\\tmp_1\\Jack\\out\\learning\\One')
('debugger_commit', 'be5b7ce08a70489c3a2ca7064e0c03834ca5d842')
('web_prediction_results', u'C:\\new_users\\tmp_1\\Jack\\out\\web_prediction_results')
('allchecks', 'C:\\temp\\Debugger\\utils\\allChecks.xml')

**Comment by DebuggerIssuesReport** [comment]
DEBUG:git.util:Failed checking if running in CYGWIN due to: WindowsError(2, 'The system cannot find the file specified')
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=C:\new_users\tmp_1\Jack\rootGit\jackrabbit-oak, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch'], cwd=C:\new_users\tmp_1\Jack\rootGit\jackrabbit-oak, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=C:\new_users\tmp_1\Jack\rootGit\jackrabbit-oak, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=C:\new_users\tmp_1\Jack\rootGit\jackrabbit-oak, universal_newlines=False, shell=None)
INFO:root:remote git at urls [u'https://github.com/apache/jackrabbit-oak'] and HEAD is on commit 06148d98cdc8daee560989976a3c41761bfb590a
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=C:\temp\Debugger, universal_newlines=False, shell=None)
INFO:root:Debugger HEAD is on commit be5b7ce08a70489c3a2ca7064e0c03834ca5d842
INFO:root:writing to \\?\C:\new_users\tmp_1\Jack\out\markers\issue_tracker_file: start time: 2019-01-22 21:56:32.975000

ERROR:root:error msg : Failed to parse: http:\\issues.apache.org\jira\projects\OAK
Traceback (most recent call last):
  File "C:\temp\Debugger\learner\utilsConf.py", line 386, in f
    ans = func(*args, **kwargs)
  File "C:\temp\Debugger\learner\wekaMethods\issuesExtract\jira_import.py", line 55, in jiraIssues
    jiraE = jira.JIRA(url)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\client.py", line 525, in __init__
    si = self.server_info()
  File "C:\Users\rotem\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\client.py", line 2425, in server_info
    j = self._get_json('serverInfo')
  File "C:\Users\rotem\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\client.py", line 2992, in _get_json
    r = self._session.get(url, params=params)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\resilientsession.py", line 151, in get
    return self.__verb('GET', url, **kwargs)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\resilientsession.py", line 125, in __verb
    response = method(url, timeout=self.timeout, **kwargs)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\requests\sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\requests\sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\rotem\Anaconda2\lib\site-packages\requests\models.py", line 309, in prepare
    self.prepare_url(url, params)
  File "C:\Users\rotem\Anaconda2\lib\site-packages\requests\models.py", line 377, in prepare_url
    raise InvalidURL(*e.args)
InvalidURL: Failed to parse: http:\\issues.apache.org\jira\projects\OAK
INFO:github3:Building a url from ('https://api.github.com', 'repos', 'BGU-AiDnD', 'Debugger')
INFO:github3:Missed the cache building the url
DEBUG:github3:GET https://api.github.com/repos/BGU-AiDnD/Debugger with {}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/BGU-AiDnD/Debugger HTTP/1.1" 200 None
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/BGU-AiDnD/Debugger', 'issues')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/BGU-AiDnD/Debugger/issues with {"body": "An Exception occurred while running Debugger:\n\ncommand line is wrapper.py antConf.txt learn\n\nTraceback (most recent call last):\n  File \"C:\\temp\\Debugger\\learner\\utilsConf.py\", line 386, in f\n    ans = func(*args, **kwargs)\n  File \"C:\\temp\\Debugger\\learner\\wekaMethods\\issuesExtract\\jira_import.py\", line 55, in jiraIssues\n    jiraE = jira.JIRA(url)\n  File \"C:\\Users\\rotem\\Anaconda2\\lib\\site-packages\\jira-2.0.1.0rc1-py2.7.egg\\jira\\client.py\", line 525, in __init__\n    si = self.server_info()\n  File \"C:\\Users\\rotem\\Anaconda2\\lib\\site-packages\\jira-2.0.1.0rc1-py2.7.egg\\jira\\client.py\", line 2425, in server_info\n    j = self._get_json('serverInfo')\n  File \"C:\\Users\\rotem\\Anaconda2\\lib\\site-packages\\jira-2.0.1.0rc1-py2.7.egg\\jira\\client.py\", line 2992, in _get_json\n    r = self._session.get(url, params=params)\n  File \"C:\\Users\\rotem\\Anaconda2\\lib\\site-packages\\jira-2.0.1.0rc1-py2.7.egg\\jira\\resilientsession.py\", line 151, in get\n    return self.__verb('GET', url, **kwargs)\n  File \"C:\\Users\\rotem\\Anaconda2\\lib\\site-packages\\jira-2.0.1.0rc1-py2.7.egg\\jira\\resilientsession.py\", line 125, in __verb\n    response = method(url, timeout=self.timeout, **kwargs)\n  File \"C:\\Users\\rotem\\Anaconda2\\lib\\site-packages\\requests\\sessions.py\", line 525, in get\n    return self.request('GET', url, **kwargs)\n  File \"C:\\Users\\rotem\\Anaconda2\\lib\\site-packages\\requests\\sessions.py\", line 498, in request\n    prep = self.prepare_request(req)\n  File \"C:\\Users\\rotem\\Anaconda2\\lib\\site-packages\\requests\\sessions.py\", line 441, in prepare_request\n    hooks=merge_hooks(request.hooks, self.hooks),\n  File \"C:\\Users\\rotem\\Anaconda2\\lib\\site-packages\\requests\\models.py\", line 309, in prepare\n    self.prepare_url(url, params)\n  File \"C:\\Users\\rotem\\Anaconda2\\lib\\site-packages\\requests\\models.py\", line 377, in prepare_url\n    raise InvalidURL(*e.args)\nInvalidURL: Failed to parse: http:\\\\issues.apache.org\\jira\\projects\\OAK\n", "assignee": "amir9979", "title": "An Exception occurred : Failed to parse: http:\\\\issues.apache.org\\jira\\projects\\OAK"}, {}
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/BGU-AiDnD/Debugger/issues HTTP/1.1" 201 8093
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/BGU-AiDnD/Debugger/issues/1037', 'comments')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/BGU-AiDnD/Debugger/issues/1037/comments with {"body": "Configuration is : \n('MethodsParsed', u'C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\commitsFiles\\\\CheckStyle.txt')\n('learning_dir', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\learning')\n('full_configure_file', 'workingDir=C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\ngit=C:\\\\new_users\\\\tmp_1\\\\Jack\\\\rootGit\\\\jackrabbit-oak\\nissue_tracker_product_name=OAK\\nissue_tracker_url=http:\\\\\\\\issues.apache.org\\\\jira\\\\projects\\\\OAK\\nissue_tracker=jira\\nvers=(0.2.1,jackrabbit-oak-0.1,jackrabbit-oak-0.10,jackrabbit-oak-0.11,jackrabbit-oak-0.12,jackrabbit-oak-0.13)')\n('docletPath', 'C:\\\\temp\\\\Debugger\\\\utils\\\\xml-doclet-1.0.4-jar-with-dependencies.jar')\n('distribution_per_version_report', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\distribution_per_version_report.csv')\n('experiments', u'C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\experiments')\n('sourceMonitorEXE', 'C:\\\\temp\\\\Debugger\\\\utils\\\\SourceMonitor.exe')\n('checkStyle57', 'C:\\\\temp\\\\Debugger\\\\utils\\\\checkstyle-5.7-all.jar')\n('distribution_per_majors_report', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\distribution_per_majors_report.csv')\n('gitPath', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\rootGit\\\\jackrabbit-oak')\n('prediction_files', {'Method': {'Most': 'prediction_Most_Method.csv', 'All': 'prediction_All_Method.csv'}, 'File': {'Most': 'prediction_Most_File.csv', 'All': 'prediction_All_File.csv'}})\n('current_dir', 'C:\\\\temp\\\\Debugger\\\\learner')\n('debugger_base_path', 'C:\\\\temp\\\\Debugger')\n('paths', ['0.2.1\\\\repo', 'jackrabbit-oak-0.1\\\\repo', 'jackrabbit-oak-0.10\\\\repo', 'jackrabbit-oak-0.11\\\\repo', 'jackrabbit-oak-0.12\\\\repo', 'jackrabbit-oak-0.13\\\\repo'])\n('versPath', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\vers')\n('buggy_repo', <git.Repo \"C:\\new_users\\tmp_1\\Jack\\rootGit\\jackrabbit-oak\\.git\">)\n('buggedType', 'File')\n('markers_dir', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\markers')\n('workingDir', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out')\n('RemoveBat', 'C:\\\\temp\\\\Debugger\\\\utils\\\\../removeBat.bat')\n('distribution_per_minors_report', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\distribution_per_minors_report.csv')\n('caching_dir', 'C:\\\\temp\\\\Debugger\\\\Debugger_cache')\n('all_but_one_dir', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\learning\\\\AllbutOne')\n('confFile', 'antConf.txt')\n('issue_tracker_product', 'OAK')\n('db_dir', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\dbAdd')\n('LocalGitPath', u'C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\repo')\n('changeFile', u'C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\commitsFiles\\\\Ins_dels.txt')\n('vers', ['0.2.1', 'jackrabbit-oak-0.1', 'jackrabbit-oak-0.10', 'jackrabbit-oak-0.11', 'jackrabbit-oak-0.12', 'jackrabbit-oak-0.13'])\n('utilsPath', 'C:\\\\temp\\\\Debugger\\\\utils')\n('checkStyle68', 'C:\\\\temp\\\\Debugger\\\\utils\\\\checkstyle-6.8-SNAPSHOT-all.jar')\n('commits', [114212489, 162817295, 186530079, 43334606, 31593055, 36590177])\n('methodsNamesXML', 'C:\\\\temp\\\\Debugger\\\\utils\\\\methodNameLines.xml')\n('vers_dirs', ['0_2_1', 'jackrabbit_oak_0_1', 'jackrabbit_oak_0_10', 'jackrabbit_oak_0_11', 'jackrabbit_oak_0_12', 'jackrabbit_oak_0_13'])\n('configuration_path', u'C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\configuration')\n('amir_tracer', 'C:\\\\temp\\\\Debugger\\\\utils\\\\uber-tracer-1.0.1-SNAPSHOT.jar')\n('distribution_report', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\distribution_report.csv')\n('weka_path', u'C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\weka')\n('granularity', 'Most')\n('vers_paths', [u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\vers\\\\0_2_1', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\vers\\\\jackrabbit_oak_0_1', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\vers\\\\jackrabbit_oak_0_10', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\vers\\\\jackrabbit_oak_0_11', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\vers\\\\jackrabbit_oak_0_12', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\vers\\\\jackrabbit_oak_0_13'])\n('configuration', <utilsConf.Configuration object at 0x0000000009829E48>)\n('bugsPath', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\bugs.csv')\n('issue_tracker', 'jira')\n('remotes_urls', [u'https://github.com/apache/jackrabbit-oak'])\n('repo', <git.Repo \"C:\\temp\\Debugger\\.git\">)\n('dates', ['2012-05-03 12:51:18', '2012-03-30 12:41:39', '2013-10-03 17:42:47', '2013-11-17 23:41:58', '2013-11-25 17:07:24', '2013-12-09 22:49:34'])\n('renamed_mapping', {})\n('versions', ['0.2.1', 'jackrabbit-oak-0.1', 'jackrabbit-oak-0.10', 'jackrabbit-oak-0.11', 'jackrabbit-oak-0.12', 'jackrabbit-oak-0.13'])\n('wekaJar', 'C:\\\\temp\\\\Debugger\\\\utils\\\\weka.jar')\n('DebuggerTests', u'C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\DebuggerTests')\n('distribution_per_micros_report', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\distribution_per_micros_report.csv')\n('issue_tracker_url', 'http:\\\\\\\\issues.apache.org\\\\jira\\\\projects\\\\OAK')\n('one_dir', u'\\\\\\\\?\\\\C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\learning\\\\One')\n('debugger_commit', 'be5b7ce08a70489c3a2ca7064e0c03834ca5d842')\n('web_prediction_results', u'C:\\\\new_users\\\\tmp_1\\\\Jack\\\\out\\\\web_prediction_results')\n('allchecks', 'C:\\\\temp\\\\Debugger\\\\utils\\\\allChecks.xml')"}, {}
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/BGU-AiDnD/Debugger/issues/1037/comments HTTP/1.1" 201 17248
INFO:github3:JSON was returned
