### ISSUE TITLE
An Exception occurred : 'module' object is not callable

### ISSUE THREAD

**Issue by DebuggerIssuesReport** [BGU-AiDnD/Debugger#1038]
An Exception occurred while running Debugger:

command line is wrapper.py C:\amirelm\projects_minors\TAJO\configuration executeTests

Traceback (most recent call last):
  File "C:\Users\amirelm\Documents\GitHub\Debugger\learner\utilsConf.py", line 386, in f
    ans = func(*args, **kwargs)
  File "wrapper.py", line 420, in executeTests
    test_runner = TestRunner(tested_repo, AmirTracer(tested_repo, utilsConf.get_configuration().amir_tracer, utilsConf.get_configuration().DebuggerTests))
  File "C:\Users\amirelm\Documents\GitHub\Debugger\learner\run_mvn.py", line 141, in __init__
    self.repo = Repo(self.git_path)
TypeError: 'module' object is not callable

**Comment by DebuggerIssuesReport** [comment]
Configuration is : 
('MethodsParsed', u'C:\\amirelm\\projects_minors\\TAJO\\commitsFiles\\CheckStyle.txt')
('learning_dir', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\learning')
('full_configure_file', 'workingDir=C:\\amirelm\\projects_minors\\TAJO\ngit=C:\\amirelm\\repos\\TAJO\nissue_tracker_product_name=TAJO\nissue_tracker_url=https://issues.apache.org/jira\nissue_tracker=jira\nvers=(release-0.2.0,release-0.8.0,release-0.9.0,release-0.10.0,release-0.11.0)')
('docletPath', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\xml-doclet-1.0.4-jar-with-dependencies.jar')
('distribution_per_version_report', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\distribution_per_version_report.csv')
('experiments', u'C:\\amirelm\\projects_minors\\TAJO\\experiments')
('sourceMonitorEXE', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\SourceMonitor.exe')
('checkStyle57', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\checkstyle-5.7-all.jar')
('distribution_per_majors_report', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\distribution_per_majors_report.csv')
('gitPath', u'\\\\?\\C:\\amirelm\\repos\\TAJO')
('prediction_files', {'Method': {'Most': 'prediction_Most_Method.csv', 'All': 'prediction_All_Method.csv'}, 'File': {'Most': 'prediction_Most_File.csv', 'All': 'prediction_All_File.csv'}})
('current_dir', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\learner')
('debugger_base_path', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger')
('paths', ['release-0.2.0\\repo', 'release-0.8.0\\repo', 'release-0.9.0\\repo', 'release-0.10.0\\repo', 'release-0.11.0\\repo'])
('versPath', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\vers')
('buggy_repo', <git.Repo "C:\amirelm\repos\TAJO\.git">)
('buggedType', 'File')
('markers_dir', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\markers')
('workingDir', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO')
('RemoveBat', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\../removeBat.bat')
('distribution_per_minors_report', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\distribution_per_minors_report.csv')
('caching_dir', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\Debugger_cache')
('all_but_one_dir', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\learning\\AllbutOne')
('confFile', 'C:\\amirelm\\projects_minors\\TAJO\\configuration')
('issue_tracker_product', 'TAJO')
('db_dir', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\dbAdd')
('LocalGitPath', u'C:\\amirelm\\projects_minors\\TAJO\\repo')
('changeFile', u'C:\\amirelm\\projects_minors\\TAJO\\commitsFiles\\Ins_dels.txt')
('vers', ['release-0.2.0', 'release-0.8.0', 'release-0.9.0', 'release-0.10.0', 'release-0.11.0'])
('utilsPath', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils')
('checkStyle68', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\checkstyle-6.8-SNAPSHOT-all.jar')
('commits', [169447716, 252720910, 114221453, 256563933, 31472776])
('methodsNamesXML', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\methodNameLines.xml')
('vers_dirs', ['release_0_2_0', 'release_0_8_0', 'release_0_9_0', 'release_0_10_0', 'release_0_11_0'])
('configuration_path', u'C:\\amirelm\\projects_minors\\TAJO\\configuration')
('amir_tracer', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\uber-tracer-1.0.1-SNAPSHOT.jar')
('distribution_report', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\distribution_report.csv')
('weka_path', u'C:\\amirelm\\projects_minors\\TAJO\\weka')
('granularity', 'Most')
('vers_paths', [u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\vers\\release_0_2_0', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\vers\\release_0_8_0', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\vers\\release_0_9_0', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\vers\\release_0_10_0', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\vers\\release_0_11_0'])
('configuration', <utilsConf.Configuration object at 0x1BC1BEF0>)
('bugsPath', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\bugs.csv')
('issue_tracker', 'jira')
('remotes_urls', [u'https://github.com/apache/tajo.git'])
('repo', <git.Repo "C:\Users\amirelm\Documents\GitHub\Debugger\.git">)
('dates', ['2015-02-24 05:48:39', '2015-10-17 08:17:23', '2013-11-01 02:53:28', '2014-04-23 12:31:49', '2014-10-12 08:23:24'])
('renamed_mapping', {})
('versions', ['release-0.2.0', 'release-0.8.0', 'release-0.9.0', 'release-0.10.0', 'release-0.11.0'])
('wekaJar', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\weka.jar')
('DebuggerTests', u'C:\\amirelm\\projects_minors\\TAJO\\DebuggerTests')
('distribution_per_micros_report', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\distribution_per_micros_report.csv')
('issue_tracker_url', 'https://issues.apache.org/jira')
('one_dir', u'\\\\?\\C:\\amirelm\\projects_minors\\TAJO\\learning\\One')
('debugger_commit', 'e5287284149d6e042edec735ae4f3c5eb8bb026e')
('web_prediction_results', u'C:\\amirelm\\projects_minors\\TAJO\\web_prediction_results')
('allchecks', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\allChecks.xml')

**Comment by DebuggerIssuesReport** [comment]
DEBUG:git.util:Failed checking if running in CYGWIN due to: WindowsError(2, 'The system cannot find the file specified')
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=C:\amirelm\repos\TAJO, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch'], cwd=C:\amirelm\repos\TAJO, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=C:\amirelm\repos\TAJO, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=C:\amirelm\repos\TAJO, universal_newlines=False, shell=None)
INFO:root:remote git at urls [u'https://github.com/apache/tajo.git'] and HEAD is on commit fb326195083959014c82c10187cb46de91ece33f
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=C:\Users\amirelm\Documents\GitHub\Debugger, universal_newlines=False, shell=None)
INFO:root:Debugger HEAD is on commit e5287284149d6e042edec735ae4f3c5eb8bb026e
INFO:root:running new process with cmdline git clone C:\amirelm\repos\TAJO repo
DEBUG:git.cmd:Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=C:\amirelm\repos\TAJO, universal_newlines=False, shell=None)
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_2_0\repo clean -fd release-0.2.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_2_0\repo checkout -f release-0.2.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_2_0\repo clean -fd release-0.2.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_8_0\repo clean -fd release-0.8.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_8_0\repo checkout -f release-0.8.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_8_0\repo clean -fd release-0.8.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_9_0\repo clean -fd release-0.9.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_9_0\repo checkout -f release-0.9.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_9_0\repo clean -fd release-0.9.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_10_0\repo clean -fd release-0.10.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_10_0\repo checkout -f release-0.10.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_10_0\repo clean -fd release-0.10.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_11_0\repo clean -fd release-0.11.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_11_0\repo checkout -f release-0.11.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects_minors\TAJO\vers\release_0_11_0\repo clean -fd release-0.11.0
INFO:root:writing to \\?\C:\amirelm\projects_minors\TAJO\markers\test_executed: start time: 2019-01-22 22:33:38.900000

ERROR:root:error msg : 'module' object is not callable
Traceback (most recent call last):
  File "C:\Users\amirelm\Documents\GitHub\Debugger\learner\utilsConf.py", line 386, in f
    ans = func(*args, **kwargs)
  File "wrapper.py", line 420, in executeTests
    test_runner = TestRunner(tested_repo, AmirTracer(tested_repo, utilsConf.get_configuration().amir_tracer, utilsConf.get_configuration().DebuggerTests))
  File "C:\Users\amirelm\Documents\GitHub\Debugger\learner\run_mvn.py", line 141, in __init__
    self.repo = Repo(self.git_path)
TypeError: 'module' object is not callable
INFO:github3:Building a url from ('https://api.github.com', 'repos', 'BGU-AiDnD', 'Debugger')
INFO:github3:Missed the cache building the url
DEBUG:github3:GET https://api.github.com/repos/BGU-AiDnD/Debugger with {}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/BGU-AiDnD/Debugger HTTP/1.1" 200 None
INFO:github3:Attempting to get JSON information from a Response with status code 200 expecting 200
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/BGU-AiDnD/Debugger', 'issues')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/BGU-AiDnD/Debugger/issues with {"body": "An Exception occurred while running Debugger:\n\ncommand line is wrapper.py C:\\amirelm\\projects_minors\\TAJO\\configuration executeTests\n\nTraceback (most recent call last):\n  File \"C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\learner\\utilsConf.py\", line 386, in f\n    ans = func(*args, **kwargs)\n  File \"wrapper.py\", line 420, in executeTests\n    test_runner = TestRunner(tested_repo, AmirTracer(tested_repo, utilsConf.get_configuration().amir_tracer, utilsConf.get_configuration().DebuggerTests))\n  File \"C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\learner\\run_mvn.py\", line 141, in __init__\n    self.repo = Repo(self.git_path)\nTypeError: 'module' object is not callable\n", "assignee": "amir9979", "title": "An Exception occurred : 'module' object is not callable"}, {}
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/BGU-AiDnD/Debugger/issues HTTP/1.1" 201 4038
INFO:github3:Attempting to get JSON information from a Response with status code 201 expecting 201
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/BGU-AiDnD/Debugger/issues/1038', 'comments')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/BGU-AiDnD/Debugger/issues/1038/comments with {"body": "Configuration is : \n('MethodsParsed', u'C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\commitsFiles\\\\CheckStyle.txt')\n('learning_dir', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\learning')\n('full_configure_file', 'workingDir=C:\\\\amirelm\\\\projects_minors\\\\TAJO\\ngit=C:\\\\amirelm\\\\repos\\\\TAJO\\nissue_tracker_product_name=TAJO\\nissue_tracker_url=https://issues.apache.org/jira\\nissue_tracker=jira\\nvers=(release-0.2.0,release-0.8.0,release-0.9.0,release-0.10.0,release-0.11.0)')\n('docletPath', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\xml-doclet-1.0.4-jar-with-dependencies.jar')\n('distribution_per_version_report', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\distribution_per_version_report.csv')\n('experiments', u'C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\experiments')\n('sourceMonitorEXE', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\SourceMonitor.exe')\n('checkStyle57', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\checkstyle-5.7-all.jar')\n('distribution_per_majors_report', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\distribution_per_majors_report.csv')\n('gitPath', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\repos\\\\TAJO')\n('prediction_files', {'Method': {'Most': 'prediction_Most_Method.csv', 'All': 'prediction_All_Method.csv'}, 'File': {'Most': 'prediction_Most_File.csv', 'All': 'prediction_All_File.csv'}})\n('current_dir', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\learner')\n('debugger_base_path', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger')\n('paths', ['release-0.2.0\\\\repo', 'release-0.8.0\\\\repo', 'release-0.9.0\\\\repo', 'release-0.10.0\\\\repo', 'release-0.11.0\\\\repo'])\n('versPath', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\vers')\n('buggy_repo', <git.Repo \"C:\\amirelm\\repos\\TAJO\\.git\">)\n('buggedType', 'File')\n('markers_dir', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\markers')\n('workingDir', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO')\n('RemoveBat', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\../removeBat.bat')\n('distribution_per_minors_report', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\distribution_per_minors_report.csv')\n('caching_dir', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\Debugger_cache')\n('all_but_one_dir', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\learning\\\\AllbutOne')\n('confFile', 'C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\configuration')\n('issue_tracker_product', 'TAJO')\n('db_dir', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\dbAdd')\n('LocalGitPath', u'C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\repo')\n('changeFile', u'C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\commitsFiles\\\\Ins_dels.txt')\n('vers', ['release-0.2.0', 'release-0.8.0', 'release-0.9.0', 'release-0.10.0', 'release-0.11.0'])\n('utilsPath', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils')\n('checkStyle68', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\checkstyle-6.8-SNAPSHOT-all.jar')\n('commits', [169447716, 252720910, 114221453, 256563933, 31472776])\n('methodsNamesXML', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\methodNameLines.xml')\n('vers_dirs', ['release_0_2_0', 'release_0_8_0', 'release_0_9_0', 'release_0_10_0', 'release_0_11_0'])\n('configuration_path', u'C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\configuration')\n('amir_tracer', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\uber-tracer-1.0.1-SNAPSHOT.jar')\n('distribution_report', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\distribution_report.csv')\n('weka_path', u'C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\weka')\n('granularity', 'Most')\n('vers_paths', [u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\vers\\\\release_0_2_0', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\vers\\\\release_0_8_0', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\vers\\\\release_0_9_0', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\vers\\\\release_0_10_0', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\vers\\\\release_0_11_0'])\n('configuration', <utilsConf.Configuration object at 0x1BC1BEF0>)\n('bugsPath', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\bugs.csv')\n('issue_tracker', 'jira')\n('remotes_urls', [u'https://github.com/apache/tajo.git'])\n('repo', <git.Repo \"C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\.git\">)\n('dates', ['2015-02-24 05:48:39', '2015-10-17 08:17:23', '2013-11-01 02:53:28', '2014-04-23 12:31:49', '2014-10-12 08:23:24'])\n('renamed_mapping', {})\n('versions', ['release-0.2.0', 'release-0.8.0', 'release-0.9.0', 'release-0.10.0', 'release-0.11.0'])\n('wekaJar', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\weka.jar')\n('DebuggerTests', u'C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\DebuggerTests')\n('distribution_per_micros_report', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\distribution_per_micros_report.csv')\n('issue_tracker_url', 'https://issues.apache.org/jira')\n('one_dir', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\learning\\\\One')\n('debugger_commit', 'e5287284149d6e042edec735ae4f3c5eb8bb026e')\n('web_prediction_results', u'C:\\\\amirelm\\\\projects_minors\\\\TAJO\\\\web_prediction_results')\n('allchecks', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\allChecks.xml')"}, {}
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/BGU-AiDnD/Debugger/issues/1038/comments HTTP/1.1" 201 17764
INFO:github3:Attempting to get JSON information from a Response with status code 201 expecting 201
INFO:github3:JSON was returned
