### ISSUE TITLE
An Exception occurred : HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

### ISSUE THREAD

**Issue by DebuggerIssuesReport** [BGU-AiDnD/Debugger#1225]
An Exception occurred while running Debugger:

command line is wrapper.py conf.txt learn

Traceback (most recent call last):
  File "D:\University - BGU\University\Debugger\learner\utilsConf.py", line 402, in f
    ans = func(*args, **kwargs)
  File "D:\University - BGU\University\Debugger\learner\wekaMethods\issuesExtract\jira_import.py", line 55, in jiraIssues
    jiraE = jira.JIRA(url)
  File "C:\Users\USER\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\client.py", line 525, in __init__
    si = self.server_info()
  File "C:\Users\USER\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\client.py", line 2425, in server_info
    j = self._get_json('serverInfo')
  File "C:\Users\USER\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\client.py", line 2992, in _get_json
    r = self._session.get(url, params=params)
  File "C:\Users\USER\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\resilientsession.py", line 151, in get
    return self.__verb('GET', url, **kwargs)
  File "C:\Users\USER\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\resilientsession.py", line 146, in __verb
    raise exception
ConnectionError: HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by DebuggerIssuesReport** [comment]
Configuration is : 
('MethodsParsed', u'D:\\University - BGU\\University\\test\\commitsFiles\\CheckStyle.txt')
('learning_dir', u'\\\\?\\D:\\University - BGU\\University\\test\\learning')
('full_configure_file', 'workingDir=D:\\University - BGU\\University\\test\ngit=D:\\University - BGU\\University\\accumulo\nissue_tracker_product_name=ACCUMULO\nissue_tracker_url=https://issue.apache.org/jira\nissue_tracker=jira\nvers=(1.6.4,rel/1.6.5, rel/1.7.1, rel/1.7.3,rel/1.8.0)')
('docletPath', 'D:\\University - BGU\\University\\Debugger\\utils\\xml-doclet-1.0.4-jar-with-dependencies.jar')
('distribution_per_version_report', u'\\\\?\\D:\\University - BGU\\University\\test\\distribution_per_version_report.csv')
('experiments', u'D:\\University - BGU\\University\\test\\experiments')
('sourceMonitorEXE', 'D:\\University - BGU\\University\\Debugger\\utils\\SourceMonitor.exe')
('checkStyle57', 'D:\\University - BGU\\University\\Debugger\\utils\\checkstyle-5.7-all.jar')
('distribution_per_majors_report', u'\\\\?\\D:\\University - BGU\\University\\test\\distribution_per_majors_report.csv')
('gitPath', u'\\\\?\\D:\\University - BGU\\University\\accumulo')
('prediction_files', {'Most': {'Method': 'prediction_Method_Most.csv', 'File': 'prediction_File_Most.csv'}, 'All': {'Method': 'prediction_Method_All.csv', 'File': 'prediction_File_All.csv'}})
('current_dir', 'D:\\University - BGU\\University\\Debugger\\learner')
('debugger_base_path', 'D:\\University - BGU\\University\\Debugger')
('paths', ['1.6.4\\repo', 'rel/1.6.5\\repo', 'rel/1.7.1\\repo', 'rel/1.7.3\\repo', 'rel/1.8.0\\repo'])
('versPath', u'\\\\?\\D:\\University - BGU\\University\\test\\vers')
('buggy_repo', <git.Repo "D:\University - BGU\University\accumulo\.git">)
('buggedType', 'Most')
('traces_dir', u'\\\\?\\D:\\University - BGU\\University\\test\\traces')
('markers_dir', u'\\\\?\\D:\\University - BGU\\University\\test\\markers')
('workingDir', u'\\\\?\\D:\\University - BGU\\University\\test')
('RemoveBat', 'D:\\University - BGU\\University\\Debugger\\utils\\../removeBat.bat')
('distribution_per_minors_report', u'\\\\?\\D:\\University - BGU\\University\\test\\distribution_per_minors_report.csv')
('caching_dir', 'D:\\University - BGU\\University\\Debugger\\Debugger_cache')
('all_but_one_dir', u'\\\\?\\D:\\University - BGU\\University\\test\\learning\\AllbutOne')
('confFile', 'conf.txt')
('issue_tracker_product', 'ACCUMULO')
('db_dir', u'\\\\?\\D:\\University - BGU\\University\\test\\dbAdd')
('LocalGitPath', u'D:\\University - BGU\\University\\test\\repo')
('changeFile', u'D:\\University - BGU\\University\\test\\commitsFiles\\Ins_dels.txt')
('vers', ['1.6.4', 'rel/1.6.5', 'rel/1.7.1', 'rel/1.7.3', 'rel/1.8.0'])
('utilsPath', 'D:\\University - BGU\\University\\Debugger\\utils')
('checkStyle68', 'D:\\University - BGU\\University\\Debugger\\utils\\checkstyle-6.8-SNAPSHOT-all.jar')
('commits', [249275636, 210425901, 48267802, 59607581, 176841513])
('methodsNamesXML', 'D:\\University - BGU\\University\\Debugger\\utils\\methodNameLines.xml')
('vers_dirs', ['1_6_4', 'rel_1_6_5', 'rel_1_7_1', 'rel_1_7_3', 'rel_1_8_0'])
('configuration_path', u'D:\\University - BGU\\University\\test\\configuration')
('amir_tracer', 'D:\\University - BGU\\University\\Debugger\\utils\\uber-tracer-1.0.1-SNAPSHOT.jar')
('distribution_report', u'\\\\?\\D:\\University - BGU\\University\\test\\distribution_report.csv')
('weka_path', u'D:\\University - BGU\\University\\test\\weka')
('granularity', 'File')
('vers_paths', [u'\\\\?\\D:\\University - BGU\\University\\test\\vers\\1_6_4', u'\\\\?\\D:\\University - BGU\\University\\test\\vers\\rel_1_6_5', u'\\\\?\\D:\\University - BGU\\University\\test\\vers\\rel_1_7_1', u'\\\\?\\D:\\University - BGU\\University\\test\\vers\\rel_1_7_3', u'\\\\?\\D:\\University - BGU\\University\\test\\vers\\rel_1_8_0'])
('configuration', <utilsConf.Configuration object at 0x0000000008BDF668>)
('bugsPath', u'\\\\?\\D:\\University - BGU\\University\\test\\bugs.csv')
('issue_tracker', 'jira')
('remotes_urls', [u'https://github.com/apache/accumulo.git'])
('repo', <git.Repo "D:\University - BGU\University\Debugger\.git">)
('dates', ['2015-09-29 02:25:05', '2016-02-13 01:01:50', '2016-02-22 23:22:34', '2017-03-10 13:48:55', '2016-09-02 19:48:57'])
('renamed_mapping', {})
('versions', ['1.6.4', 'rel/1.6.5', 'rel/1.7.1', 'rel/1.7.3', 'rel/1.8.0'])
('wekaJar', 'D:\\University - BGU\\University\\Debugger\\utils\\weka.jar')
('DebuggerTests', u'D:\\University - BGU\\University\\test\\DebuggerTests')
('distribution_per_micros_report', u'\\\\?\\D:\\University - BGU\\University\\test\\distribution_per_micros_report.csv')
('issue_tracker_url', 'https://issue.apache.org/jira')
('one_dir', u'\\\\?\\D:\\University - BGU\\University\\test\\learning\\One')
('debugger_commit', '520f228039debf97ae94b5b2d7fe068beaedcab0')
('web_prediction_results', u'D:\\University - BGU\\University\\test\\web_prediction_results')
('allchecks', 'D:\\University - BGU\\University\\Debugger\\utils\\allChecks.xml')

**Comment by DebuggerIssuesReport** [comment]
DEBUG:git.util:Failed checking if running in CYGWIN due to: WindowsError(2, 'The system cannot find the file specified')
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=D:\University - BGU\University\accumulo, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch'], cwd=D:\University - BGU\University\accumulo, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=D:\University - BGU\University\accumulo, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=D:\University - BGU\University\accumulo, universal_newlines=False, shell=None)
INFO:root:remote git at urls [u'https://github.com/apache/accumulo.git'] and HEAD is on commit fc2b8f06970e8c0609fb33927f2ca23e8771cb68
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=D:\University - BGU\University\Debugger, universal_newlines=False, shell=None)
INFO:root:Debugger HEAD is on commit 520f228039debf97ae94b5b2d7fe068beaedcab0
INFO:root:writing to \\?\D:\University - BGU\University\test\markers\issue_tracker_file: start time: 2019-04-07 14:50:46.882000

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): issue.apache.org:443
WARNING:root:HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F0F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)) while doing GET https://issue.apache.org/jira/rest/api/2/serverInfo [{u'headers': {'Accept-Encoding': 'gzip, deflate', u'Accept': u'application/json,*.*;q=0.9', 'User-Agent': 'python-requests/2.21.0', 'Connection': 'keep-alive', u'X-Atlassian-Token': u'no-check', u'Cache-Control': u'no-cache', u'Content-Type': u'application/json'}, 'params': None}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F0F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))] errno:None on GET https://issue.apache.org/jira/rest/api/2/serverInfo
{'request': <PreparedRequest [GET]>, 'response': None}
{'request': <PreparedRequest [GET]>, 'response': None}
WARNING:root:Got recoverable error from GET https://issue.apache.org/jira/rest/api/2/serverInfo, will retry [1/3] in 11.9960283437s. Err: HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F0F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (2): issue.apache.org:443
WARNING:root:HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)) while doing GET https://issue.apache.org/jira/rest/api/2/serverInfo [{u'headers': {'Accept-Encoding': 'gzip, deflate', u'Accept': u'application/json,*.*;q=0.9', 'User-Agent': 'python-requests/2.21.0', 'Connection': 'keep-alive', u'X-Atlassian-Token': u'no-check', u'Cache-Control': u'no-cache', u'Content-Type': u'application/json'}, 'params': None}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))] errno:None on GET https://issue.apache.org/jira/rest/api/2/serverInfo
{'request': <PreparedRequest [GET]>, 'response': None}
{'request': <PreparedRequest [GET]>, 'response': None}
WARNING:root:Got recoverable error from GET https://issue.apache.org/jira/rest/api/2/serverInfo, will retry [2/3] in 5.56969672144s. Err: HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (3): issue.apache.org:443
WARNING:root:HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F128>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)) while doing GET https://issue.apache.org/jira/rest/api/2/serverInfo [{u'headers': {'Accept-Encoding': 'gzip, deflate', u'Accept': u'application/json,*.*;q=0.9', 'User-Agent': 'python-requests/2.21.0', 'Connection': 'keep-alive', u'X-Atlassian-Token': u'no-check', u'Cache-Control': u'no-cache', u'Content-Type': u'application/json'}, 'params': None}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F128>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))] errno:None on GET https://issue.apache.org/jira/rest/api/2/serverInfo
{'request': <PreparedRequest [GET]>, 'response': None}
{'request': <PreparedRequest [GET]>, 'response': None}
WARNING:root:Got recoverable error from GET https://issue.apache.org/jira/rest/api/2/serverInfo, will retry [3/3] in 58.587025677s. Err: HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F128>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (4): issue.apache.org:443
WARNING:root:HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)) while doing GET https://issue.apache.org/jira/rest/api/2/serverInfo [{u'headers': {'Accept-Encoding': 'gzip, deflate', u'Accept': u'application/json,*.*;q=0.9', 'User-Agent': 'python-requests/2.21.0', 'Connection': 'keep-alive', u'X-Atlassian-Token': u'no-check', u'Cache-Control': u'no-cache', u'Content-Type': u'application/json'}, 'params': None}]
ERROR:root:error msg : HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Traceback (most recent call last):
  File "D:\University - BGU\University\Debugger\learner\utilsConf.py", line 402, in f
    ans = func(*args, **kwargs)
  File "D:\University - BGU\University\Debugger\learner\wekaMethods\issuesExtract\jira_import.py", line 55, in jiraIssues
    jiraE = jira.JIRA(url)
  File "C:\Users\USER\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\client.py", line 525, in __init__
    si = self.server_info()
  File "C:\Users\USER\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\client.py", line 2425, in server_info
    j = self._get_json('serverInfo')
  File "C:\Users\USER\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\client.py", line 2992, in _get_json
    r = self._session.get(url, params=params)
  File "C:\Users\USER\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\resilientsession.py", line 151, in get
    return self.__verb('GET', url, **kwargs)
  File "C:\Users\USER\Anaconda2\lib\site-packages\jira-2.0.1.0rc1-py2.7.egg\jira\resilientsession.py", line 146, in __verb
    raise exception
ConnectionError: HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
INFO:github3:Building a url from ('https://api.github.com', 'repos', 'BGU-AiDnD', 'Debugger')
INFO:github3:Missed the cache building the url
DEBUG:github3:GET https://api.github.com/repos/BGU-AiDnD/Debugger with {}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/BGU-AiDnD/Debugger HTTP/1.1" 200 None
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/BGU-AiDnD/Debugger', 'issues')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/BGU-AiDnD/Debugger/issues with {"body": "An Exception occurred while running Debugger:\n\ncommand line is wrapper.py conf.txt learn\n\nTraceback (most recent call last):\n  File \"D:\\University - BGU\\University\\Debugger\\learner\\utilsConf.py\", line 402, in f\n    ans = func(*args, **kwargs)\n  File \"D:\\University - BGU\\University\\Debugger\\learner\\wekaMethods\\issuesExtract\\jira_import.py\", line 55, in jiraIssues\n    jiraE = jira.JIRA(url)\n  File \"C:\\Users\\USER\\Anaconda2\\lib\\site-packages\\jira-2.0.1.0rc1-py2.7.egg\\jira\\client.py\", line 525, in __init__\n    si = self.server_info()\n  File \"C:\\Users\\USER\\Anaconda2\\lib\\site-packages\\jira-2.0.1.0rc1-py2.7.egg\\jira\\client.py\", line 2425, in server_info\n    j = self._get_json('serverInfo')\n  File \"C:\\Users\\USER\\Anaconda2\\lib\\site-packages\\jira-2.0.1.0rc1-py2.7.egg\\jira\\client.py\", line 2992, in _get_json\n    r = self._session.get(url, params=params)\n  File \"C:\\Users\\USER\\Anaconda2\\lib\\site-packages\\jira-2.0.1.0rc1-py2.7.egg\\jira\\resilientsession.py\", line 151, in get\n    return self.__verb('GET', url, **kwargs)\n  File \"C:\\Users\\USER\\Anaconda2\\lib\\site-packages\\jira-2.0.1.0rc1-py2.7.egg\\jira\\resilientsession.py\", line 146, in __verb\n    raise exception\nConnectionError: HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))\n", "assignee": "amir9979", "title": "An Exception occurred : HTTPSConnectionPool(host='issue.apache.org', port=443): Max retries exceeded with url: /jira/rest/api/2/serverInfo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000009E6F208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))"}, {}
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/BGU-AiDnD/Debugger/issues HTTP/1.1" 201 6872
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/BGU-AiDnD/Debugger/issues/1225', 'comments')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/BGU-AiDnD/Debugger/issues/1225/comments with {"body": "Configuration is : \n('MethodsParsed', u'D:\\\\University - BGU\\\\University\\\\test\\\\commitsFiles\\\\CheckStyle.txt')\n('learning_dir', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\learning')\n('full_configure_file', 'workingDir=D:\\\\University - BGU\\\\University\\\\test\\ngit=D:\\\\University - BGU\\\\University\\\\accumulo\\nissue_tracker_product_name=ACCUMULO\\nissue_tracker_url=https://issue.apache.org/jira\\nissue_tracker=jira\\nvers=(1.6.4,rel/1.6.5, rel/1.7.1, rel/1.7.3,rel/1.8.0)')\n('docletPath', 'D:\\\\University - BGU\\\\University\\\\Debugger\\\\utils\\\\xml-doclet-1.0.4-jar-with-dependencies.jar')\n('distribution_per_version_report', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\distribution_per_version_report.csv')\n('experiments', u'D:\\\\University - BGU\\\\University\\\\test\\\\experiments')\n('sourceMonitorEXE', 'D:\\\\University - BGU\\\\University\\\\Debugger\\\\utils\\\\SourceMonitor.exe')\n('checkStyle57', 'D:\\\\University - BGU\\\\University\\\\Debugger\\\\utils\\\\checkstyle-5.7-all.jar')\n('distribution_per_majors_report', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\distribution_per_majors_report.csv')\n('gitPath', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\accumulo')\n('prediction_files', {'Most': {'Method': 'prediction_Method_Most.csv', 'File': 'prediction_File_Most.csv'}, 'All': {'Method': 'prediction_Method_All.csv', 'File': 'prediction_File_All.csv'}})\n('current_dir', 'D:\\\\University - BGU\\\\University\\\\Debugger\\\\learner')\n('debugger_base_path', 'D:\\\\University - BGU\\\\University\\\\Debugger')\n('paths', ['1.6.4\\\\repo', 'rel/1.6.5\\\\repo', 'rel/1.7.1\\\\repo', 'rel/1.7.3\\\\repo', 'rel/1.8.0\\\\repo'])\n('versPath', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\vers')\n('buggy_repo', <git.Repo \"D:\\University - BGU\\University\\accumulo\\.git\">)\n('buggedType', 'Most')\n('traces_dir', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\traces')\n('markers_dir', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\markers')\n('workingDir', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test')\n('RemoveBat', 'D:\\\\University - BGU\\\\University\\\\Debugger\\\\utils\\\\../removeBat.bat')\n('distribution_per_minors_report', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\distribution_per_minors_report.csv')\n('caching_dir', 'D:\\\\University - BGU\\\\University\\\\Debugger\\\\Debugger_cache')\n('all_but_one_dir', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\learning\\\\AllbutOne')\n('confFile', 'conf.txt')\n('issue_tracker_product', 'ACCUMULO')\n('db_dir', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\dbAdd')\n('LocalGitPath', u'D:\\\\University - BGU\\\\University\\\\test\\\\repo')\n('changeFile', u'D:\\\\University - BGU\\\\University\\\\test\\\\commitsFiles\\\\Ins_dels.txt')\n('vers', ['1.6.4', 'rel/1.6.5', 'rel/1.7.1', 'rel/1.7.3', 'rel/1.8.0'])\n('utilsPath', 'D:\\\\University - BGU\\\\University\\\\Debugger\\\\utils')\n('checkStyle68', 'D:\\\\University - BGU\\\\University\\\\Debugger\\\\utils\\\\checkstyle-6.8-SNAPSHOT-all.jar')\n('commits', [249275636, 210425901, 48267802, 59607581, 176841513])\n('methodsNamesXML', 'D:\\\\University - BGU\\\\University\\\\Debugger\\\\utils\\\\methodNameLines.xml')\n('vers_dirs', ['1_6_4', 'rel_1_6_5', 'rel_1_7_1', 'rel_1_7_3', 'rel_1_8_0'])\n('configuration_path', u'D:\\\\University - BGU\\\\University\\\\test\\\\configuration')\n('amir_tracer', 'D:\\\\University - BGU\\\\University\\\\Debugger\\\\utils\\\\uber-tracer-1.0.1-SNAPSHOT.jar')\n('distribution_report', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\distribution_report.csv')\n('weka_path', u'D:\\\\University - BGU\\\\University\\\\test\\\\weka')\n('granularity', 'File')\n('vers_paths', [u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\vers\\\\1_6_4', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\vers\\\\rel_1_6_5', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\vers\\\\rel_1_7_1', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\vers\\\\rel_1_7_3', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\vers\\\\rel_1_8_0'])\n('configuration', <utilsConf.Configuration object at 0x0000000008BDF668>)\n('bugsPath', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\bugs.csv')\n('issue_tracker', 'jira')\n('remotes_urls', [u'https://github.com/apache/accumulo.git'])\n('repo', <git.Repo \"D:\\University - BGU\\University\\Debugger\\.git\">)\n('dates', ['2015-09-29 02:25:05', '2016-02-13 01:01:50', '2016-02-22 23:22:34', '2017-03-10 13:48:55', '2016-09-02 19:48:57'])\n('renamed_mapping', {})\n('versions', ['1.6.4', 'rel/1.6.5', 'rel/1.7.1', 'rel/1.7.3', 'rel/1.8.0'])\n('wekaJar', 'D:\\\\University - BGU\\\\University\\\\Debugger\\\\utils\\\\weka.jar')\n('DebuggerTests', u'D:\\\\University - BGU\\\\University\\\\test\\\\DebuggerTests')\n('distribution_per_micros_report', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\distribution_per_micros_report.csv')\n('issue_tracker_url', 'https://issue.apache.org/jira')\n('one_dir', u'\\\\\\\\?\\\\D:\\\\University - BGU\\\\University\\\\test\\\\learning\\\\One')\n('debugger_commit', '520f228039debf97ae94b5b2d7fe068beaedcab0')\n('web_prediction_results', u'D:\\\\University - BGU\\\\University\\\\test\\\\web_prediction_results')\n('allchecks', 'D:\\\\University - BGU\\\\University\\\\Debugger\\\\utils\\\\allChecks.xml')"}, {}
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/BGU-AiDnD/Debugger/issues/1225/comments HTTP/1.1" 201 17636
INFO:github3:JSON was returned
