### ISSUE TITLE
An Exception occurred : invalid literal for int() with base 10: 'O extends ListOptions'

### ISSUE THREAD

**Issue by DebuggerIssuesReport** [BGU-AiDnD/Debugger#236]
An Exception occurred while running Debugger:

command line is wrapper.py C:\amirelm\apache_projects\jclouds.txt learn

Traceback (most recent call last):
  File "C:\Users\amirelm\Documents\GitHub\Debugger\learner\utilsConf.py", line 293, in f
    ans = func(*args, **kwargs)
  File "wrapper.py", line 360, in wrapperLearner
    createBuildMLModels()
  File "C:\Users\amirelm\Documents\GitHub\Debugger\learner\utilsConf.py", line 293, in f
    ans = func(*args, **kwargs)
  File "wrapper.py", line 233, in createBuildMLModels
    utilsConf.get_configuration().gitPath, utilsConf.get_configuration().weka_path, utilsConf.get_configuration().vers, utilsConf.get_configuration().vers_dirs, buggedType, utilsConf.get_configuration().db_dir)
  File "C:\Users\amirelm\Documents\GitHub\Debugger\learner\wekaMethods\articles.py", line 861, in articlesAllpacks
    arffCreate(dbPath, FeaturesClasses, vers_dirs, dates, bugQ, wanted, trainingFile, testingFile, NamesFile)
  File "C:\Users\amirelm\Documents\GitHub\Debugger\learner\wekaMethods\articles.py", line 553, in arffCreate
    tag, allNames = arffCreateForTag(dbpath, dates, i, objects, bugQ, wanted)
  File "C:\Users\amirelm\Documents\GitHub\Debugger\learner\wekaMethods\articles.py", line 355, in arffCreateForTag
    o.get_features(c, files_dict, prev_date, start_date, end_date)
  File "C:\Users\amirelm\Documents\GitHub\Debugger\learner\wekaMethods\features\sourceMonitor.py", line 88, in get_features
    complexity_d[name].append(int(row[1]))
ValueError: invalid literal for int() with base 10: 'O extends ListOptions'

**Comment by DebuggerIssuesReport** [comment]
Configuration is : 
('MethodsParsed', u'\\\\?\\C:\\amirelm\\apache_projects\\jcloudsWORKING24\\repo\\commitsFiles\\CheckStyle.txt')
('full_configure_file', 'workingDir=C:\\amirelm\\apache_projects\\jcloudsWORKING24\ngit=C:\\temp\\clones\\jclouds\nissue_tracker_product_name=JCLOUDS\nissue_tracker_url=https://issues.apache.org/jira\nissue_tracker=jira\nvers=(rel/jclouds-2.0.0,rel/jclouds-2.0.0-rc3, rel/jclouds-2.0.1-rc1, rel/jclouds-2.0.2,rel/jclouds-2.0.3)\n')
('docletPath', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\xml-doclet-1.0.4-jar-with-dependencies.jar')
('sourceMonitorEXE', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\SourceMonitor.exe')
('checkStyle57', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\checkstyle-5.7-all.jar')
('gitPath', u'\\\\?\\C:\\temp\\clones\\jclouds')
('debugger_base_path', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger')
('paths', ['rel/jclouds-2.0.0\\repo', 'rel/jclouds-2.0.0-rc3\\repo', 'rel/jclouds-2.0.1-rc1\\repo', 'rel/jclouds-2.0.2\\repo', 'rel/jclouds-2.0.3\\repo'])
('versPath', u'\\\\?\\C:\\amirelm\\apache_projects\\jcloudsWORKING24\\vers')
('markers_dir', u'\\\\?\\C:\\amirelm\\apache_projects\\jcloudsWORKING24\\markers')
('workingDir', u'\\\\?\\C:\\amirelm\\apache_projects\\jcloudsWORKING24')
('RemoveBat', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\../removeBat.bat')
('issue_tracker_product', 'JCLOUDS')
('db_dir', u'\\\\?\\C:\\amirelm\\apache_projects\\jcloudsWORKING24\\dbAdd')
('LocalGitPath', u'\\\\?\\C:\\amirelm\\apache_projects\\jcloudsWORKING24\\repo')
('changeFile', u'\\\\?\\C:\\amirelm\\apache_projects\\jcloudsWORKING24\\repo\\commitsFiles\\Ins_dels.txt')
('vers', ['rel/jclouds-2.0.0', 'rel/jclouds-2.0.0-rc3', 'rel/jclouds-2.0.1-rc1', 'rel/jclouds-2.0.2', 'rel/jclouds-2.0.3'])
('utilsPath', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils')
('checkStyle68', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\checkstyle-6.8-SNAPSHOT-all.jar')
('commits', [111387519, 111387519, 106551177, 91539452, 16288216])
('methodsNamesXML', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\methodNameLines.xml')
('vers_dirs', ['rel_jclouds_2_0_0', 'rel_jclouds_2_0_0_rc3', 'rel_jclouds_2_0_1_rc1', 'rel_jclouds_2_0_2', 'rel_jclouds_2_0_3'])
('weka_path', u'C:\\amirelm\\apache_projects\\jcloudsWORKING24\\weka')
('vers_paths', [u'\\\\?\\C:\\amirelm\\apache_projects\\jcloudsWORKING24\\vers\\rel_jclouds_2_0_0', u'\\\\?\\C:\\amirelm\\apache_projects\\jcloudsWORKING24\\vers\\rel_jclouds_2_0_0_rc3', u'\\\\?\\C:\\amirelm\\apache_projects\\jcloudsWORKING24\\vers\\rel_jclouds_2_0_1_rc1', u'\\\\?\\C:\\amirelm\\apache_projects\\jcloudsWORKING24\\vers\\rel_jclouds_2_0_2', u'\\\\?\\C:\\amirelm\\apache_projects\\jcloudsWORKING24\\vers\\rel_jclouds_2_0_3'])
('bugsPath', u'\\\\?\\C:\\amirelm\\apache_projects\\jcloudsWORKING24\\bugs.csv')
('issue_tracker', 'jira')
('dates', ['2016-11-09 23:30:45', '2016-11-09 23:30:45', '2017-02-17 15:37:54', '2017-06-29 13:21:59', '2017-11-25 23:28:20'])
('versions', ['rel/jclouds-2.0.0', 'rel/jclouds-2.0.0-rc3', 'rel/jclouds-2.0.1-rc1', 'rel/jclouds-2.0.2', 'rel/jclouds-2.0.3'])
('wekaJar', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\weka.jar')
('issue_tracker_url', 'https://issues.apache.org/jira')
('web_prediction_results', u'C:\\amirelm\\apache_projects\\jcloudsWORKING24\\web_prediction_results')
('allchecks', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\allChecks.xml')
