### ISSUE TITLE
An Exception occurred : global name 'weka' is not defined

### ISSUE THREAD

**Issue by DebuggerIssuesReport** [BGU-AiDnD/Debugger#359]
An Exception occurred while running Debugger:

command line is wrapper.py antConf.txt

Traceback (most recent call last):
  File "C:\new_users\tester\six\rootLearn\Debugger\learner\utilsConf.py", line 305, in f
    ans = func(*args, **kwargs)
  File "wrapper.py", line 378, in executeTests
    for x in [tested_repo, weka, tracer_path]:
NameError: global name 'weka' is not defined

**Comment by DebuggerIssuesReport** [comment]
Configuration is : 
('MethodsParsed', u'\\\\?\\Z:\\tester\\six\\out\\repo\\commitsFiles\\CheckStyle.txt')
('full_configure_file', 'workingDir=Z:\\tester\\six\\out\ngit=Z:\\tester\\six\\rootGit\\ant\nissue_tracker_product_name=Ant\nissue_tracker_url=bz.apache.org/bugzilla\nissue_tracker=bugzilla\nvers=(ANT_170,ANT_171_B1,ANT_180,ANT_182,ANT_183)')
('docletPath', 'C:\\new_users\\tester\\six\\rootLearn\\Debugger\\utils\\xml-doclet-1.0.4-jar-with-dependencies.jar')
('sourceMonitorEXE', 'C:\\new_users\\tester\\six\\rootLearn\\Debugger\\utils\\SourceMonitor.exe')
('checkStyle57', 'C:\\new_users\\tester\\six\\rootLearn\\Debugger\\utils\\checkstyle-5.7-all.jar')
('gitPath', u'\\\\?\\Z:\\tester\\six\\rootGit\\ant')
('debugger_base_path', 'C:\\new_users\\tester\\six\\rootLearn\\Debugger')
('paths', ['ANT_170\\repo', 'ANT_171_B1\\repo', 'ANT_180\\repo', 'ANT_182\\repo', 'ANT_183\\repo'])
('versPath', u'\\\\?\\Z:\\tester\\six\\out\\vers')
('markers_dir', u'\\\\?\\Z:\\tester\\six\\out\\markers')
('workingDir', u'\\\\?\\Z:\\tester\\six\\out')
('RemoveBat', 'C:\\new_users\\tester\\six\\rootLearn\\Debugger\\utils\\../removeBat.bat')
('caching_dir', 'C:\\new_users\\tester\\six\\rootLearn\\Debugger\\Debugger_cache')
('issue_tracker_product', 'Ant')
('db_dir', u'\\\\?\\Z:\\tester\\six\\out\\dbAdd')
('LocalGitPath', u'\\\\?\\Z:\\tester\\six\\out\\repo')
('changeFile', u'\\\\?\\Z:\\tester\\six\\out\\repo\\commitsFiles\\Ins_dels.txt')
('vers', ['ANT_170', 'ANT_171_B1', 'ANT_180', 'ANT_182', 'ANT_183'])
('utilsPath', 'C:\\new_users\\tester\\six\\rootLearn\\Debugger\\utils')
('checkStyle68', 'C:\\new_users\\tester\\six\\rootLearn\\Debugger\\utils\\checkstyle-6.8-SNAPSHOT-all.jar')
('commits', [113239925, 158498672, 131138728, 215269690, 39793897])
('methodsNamesXML', 'C:\\new_users\\tester\\six\\rootLearn\\Debugger\\utils\\methodNameLines.xml')
('vers_dirs', ['ANT_170', 'ANT_171_B1', 'ANT_180', 'ANT_182', 'ANT_183'])
('configuration_path', u'Z:\\tester\\six\\out\\configuration')
('amir_tracer', 'C:\\new_users\\tester\\six\\rootLearn\\Debugger\\utils\\uber-tracer-1.0.1-SNAPSHOT.jar')
('weka_path', u'Z:\\tester\\six\\out\\weka')
('vers_paths', [u'\\\\?\\Z:\\tester\\six\\out\\vers\\ANT_170', u'\\\\?\\Z:\\tester\\six\\out\\vers\\ANT_171_B1', u'\\\\?\\Z:\\tester\\six\\out\\vers\\ANT_180', u'\\\\?\\Z:\\tester\\six\\out\\vers\\ANT_182', u'\\\\?\\Z:\\tester\\six\\out\\vers\\ANT_183'])
('bugsPath', u'\\\\?\\Z:\\tester\\six\\out\\bugs.csv')
('issue_tracker', 'bugzilla')
('dates', ['2007-10-29 19:30:35', '2008-03-13 05:15:16', '2010-02-02 02:49:23', '2010-12-20 20:59:29', '2012-02-25 21:19:07'])
('versions', ['ANT_170', 'ANT_171_B1', 'ANT_180', 'ANT_182', 'ANT_183'])
('wekaJar', 'C:\\new_users\\tester\\six\\rootLearn\\Debugger\\utils\\weka.jar')
('issue_tracker_url', 'bz.apache.org/bugzilla')
('web_prediction_results', u'Z:\\tester\\six\\out\\web_prediction_results')
('allchecks', 'C:\\new_users\\tester\\six\\rootLearn\\Debugger\\utils\\allChecks.xml')

**Comment by DebuggerIssuesReport** [comment]
DEBUG:git.util:Failed checking if running in CYGWIN due to: WindowsError(2, 'The system cannot find the file specified')
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=\\?\Z:\tester\six\rootGit\ant, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch'], cwd=\\?\Z:\tester\six\rootGit\ant, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=C:\new_users\tester\six\rootLearn\Debugger, universal_newlines=False, shell=None)
INFO:root:Debugger HEAD is on commit a02008c67a65f8dd1058ead88c6fbb46695ad8e8
DEBUG:git.cmd:Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=\\?\Z:\tester\six\rootGit\ant, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=\\?\Z:\tester\six\rootGit\ant, universal_newlines=False, shell=None)
INFO:root:remote git at urls [u'https://git-wip-us.apache.org/repos/asf/ant.git'] and HEAD is on commit cd4c13a2a35521c84227fbf3aee1c6065283cf7f
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_170\repo clean -fd ANT_170
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_170\repo checkout -f ANT_170
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_170\repo clean -fd ANT_170
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_171_B1\repo clean -fd ANT_171_B1
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_171_B1\repo checkout -f ANT_171_B1
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_171_B1\repo clean -fd ANT_171_B1
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_180\repo clean -fd ANT_180
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_180\repo checkout -f ANT_180
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_180\repo clean -fd ANT_180
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_182\repo clean -fd ANT_182
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_182\repo checkout -f ANT_182
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_182\repo clean -fd ANT_182
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_183\repo clean -fd ANT_183
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_183\repo checkout -f ANT_183
INFO:root:running new process with cmdline git -C \\?\Z:\tester\six\out\vers\ANT_183\repo clean -fd ANT_183
INFO:root:running new process with cmdline git clone Z:\tester\six\rootGit\ant repo
INFO:root:writing to \\?\Z:\tester\six\out\markers\test_executed: start time: 2018-08-21 18:38:33.808000

ERROR:root:error msg : global name 'weka' is not defined
Traceback (most recent call last):
  File "C:\new_users\tester\six\rootLearn\Debugger\learner\utilsConf.py", line 305, in f
    ans = func(*args, **kwargs)
  File "wrapper.py", line 378, in executeTests
    for x in [tested_repo, weka, tracer_path]:
NameError: global name 'weka' is not defined
INFO:github3:Building a url from ('https://api.github.com', 'repos', 'amir9979', 'Debugger')
INFO:github3:Missed the cache building the url
DEBUG:github3:GET https://api.github.com/repos/amir9979/Debugger with {}
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.github.com:443 "GET /repos/amir9979/Debugger HTTP/1.1" 200 None
INFO:github3:Attempting to get JSON information from a Response with status code 200 expecting 200
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/amir9979/Debugger', 'issues')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/amir9979/Debugger/issues with {"body": "An Exception occurred while running Debugger:\n\ncommand line is wrapper.py antConf.txt\n\nTraceback (most recent call last):\n  File \"C:\\new_users\\tester\\six\\rootLearn\\Debugger\\learner\\utilsConf.py\", line 305, in f\n    ans = func(*args, **kwargs)\n  File \"wrapper.py\", line 378, in executeTests\n    for x in [tested_repo, weka, tracer_path]:\nNameError: global name 'weka' is not defined\n", "assignee": "amir9979", "title": "An Exception occurred : global name 'weka' is not defined"}, {}
DEBUG:requests.packages.urllib3.connectionpool:https://api.github.com:443 "POST /repos/amir9979/Debugger/issues HTTP/1.1" 201 3129
INFO:github3:Attempting to get JSON information from a Response with status code 201 expecting 201
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/amir9979/Debugger/issues/359', 'comments')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/amir9979/Debugger/issues/359/comments with {"body": "Configuration is : \n('MethodsParsed', u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\out\\\\repo\\\\commitsFiles\\\\CheckStyle.txt')\n('full_configure_file', 'workingDir=Z:\\\\tester\\\\six\\\\out\\ngit=Z:\\\\tester\\\\six\\\\rootGit\\\\ant\\nissue_tracker_product_name=Ant\\nissue_tracker_url=bz.apache.org/bugzilla\\nissue_tracker=bugzilla\\nvers=(ANT_170,ANT_171_B1,ANT_180,ANT_182,ANT_183)')\n('docletPath', 'C:\\\\new_users\\\\tester\\\\six\\\\rootLearn\\\\Debugger\\\\utils\\\\xml-doclet-1.0.4-jar-with-dependencies.jar')\n('sourceMonitorEXE', 'C:\\\\new_users\\\\tester\\\\six\\\\rootLearn\\\\Debugger\\\\utils\\\\SourceMonitor.exe')\n('checkStyle57', 'C:\\\\new_users\\\\tester\\\\six\\\\rootLearn\\\\Debugger\\\\utils\\\\checkstyle-5.7-all.jar')\n('gitPath', u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\rootGit\\\\ant')\n('debugger_base_path', 'C:\\\\new_users\\\\tester\\\\six\\\\rootLearn\\\\Debugger')\n('paths', ['ANT_170\\\\repo', 'ANT_171_B1\\\\repo', 'ANT_180\\\\repo', 'ANT_182\\\\repo', 'ANT_183\\\\repo'])\n('versPath', u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\out\\\\vers')\n('markers_dir', u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\out\\\\markers')\n('workingDir', u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\out')\n('RemoveBat', 'C:\\\\new_users\\\\tester\\\\six\\\\rootLearn\\\\Debugger\\\\utils\\\\../removeBat.bat')\n('caching_dir', 'C:\\\\new_users\\\\tester\\\\six\\\\rootLearn\\\\Debugger\\\\Debugger_cache')\n('issue_tracker_product', 'Ant')\n('db_dir', u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\out\\\\dbAdd')\n('LocalGitPath', u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\out\\\\repo')\n('changeFile', u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\out\\\\repo\\\\commitsFiles\\\\Ins_dels.txt')\n('vers', ['ANT_170', 'ANT_171_B1', 'ANT_180', 'ANT_182', 'ANT_183'])\n('utilsPath', 'C:\\\\new_users\\\\tester\\\\six\\\\rootLearn\\\\Debugger\\\\utils')\n('checkStyle68', 'C:\\\\new_users\\\\tester\\\\six\\\\rootLearn\\\\Debugger\\\\utils\\\\checkstyle-6.8-SNAPSHOT-all.jar')\n('commits', [113239925, 158498672, 131138728, 215269690, 39793897])\n('methodsNamesXML', 'C:\\\\new_users\\\\tester\\\\six\\\\rootLearn\\\\Debugger\\\\utils\\\\methodNameLines.xml')\n('vers_dirs', ['ANT_170', 'ANT_171_B1', 'ANT_180', 'ANT_182', 'ANT_183'])\n('configuration_path', u'Z:\\\\tester\\\\six\\\\out\\\\configuration')\n('amir_tracer', 'C:\\\\new_users\\\\tester\\\\six\\\\rootLearn\\\\Debugger\\\\utils\\\\uber-tracer-1.0.1-SNAPSHOT.jar')\n('weka_path', u'Z:\\\\tester\\\\six\\\\out\\\\weka')\n('vers_paths', [u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\out\\\\vers\\\\ANT_170', u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\out\\\\vers\\\\ANT_171_B1', u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\out\\\\vers\\\\ANT_180', u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\out\\\\vers\\\\ANT_182', u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\out\\\\vers\\\\ANT_183'])\n('bugsPath', u'\\\\\\\\?\\\\Z:\\\\tester\\\\six\\\\out\\\\bugs.csv')\n('issue_tracker', 'bugzilla')\n('dates', ['2007-10-29 19:30:35', '2008-03-13 05:15:16', '2010-02-02 02:49:23', '2010-12-20 20:59:29', '2012-02-25 21:19:07'])\n('versions', ['ANT_170', 'ANT_171_B1', 'ANT_180', 'ANT_182', 'ANT_183'])\n('wekaJar', 'C:\\\\new_users\\\\tester\\\\six\\\\rootLearn\\\\Debugger\\\\utils\\\\weka.jar')\n('issue_tracker_url', 'bz.apache.org/bugzilla')\n('web_prediction_results', u'Z:\\\\tester\\\\six\\\\out\\\\web_prediction_results')\n('allchecks', 'C:\\\\new_users\\\\tester\\\\six\\\\rootLearn\\\\Debugger\\\\utils\\\\allChecks.xml')"}, {}
DEBUG:requests.packages.urllib3.connectionpool:https://api.github.com:443 "POST /repos/amir9979/Debugger/issues/359/comments HTTP/1.1" 201 11100
INFO:github3:Attempting to get JSON information from a Response with status code 201 expecting 201
INFO:github3:JSON was returned
