### ISSUE TITLE
An Exception occurred : org.apache.flink.hadoop.shaded.com.google.common.collect.iterators

### ISSUE THREAD

**Issue by DebuggerIssuesReport** [BGU-AiDnD/Debugger#467]
An Exception occurred while running Debugger:

command line is C:/Users/amirelm/Documents/GitHub/Debugger/learner/wrapper.py C:\Users\amirelm\Documents\GitHub\repository_mining\repository_data\configurations\FLINK_8

Traceback (most recent call last):
  File "C:/Users/amirelm/Documents/GitHub/Debugger/learner\utilsConf.py", line 311, in f
    ans = func(*args, **kwargs)
  File "C:/Users/amirelm/Documents/GitHub/Debugger/learner/wrapper.py", line 538, in wrapperAll
    create_experiment(executeTests())
  File "C:/Users/amirelm/Documents/GitHub/Debugger/learner/wrapper.py", line 529, in create_experiment
    eg = ExperimentGenerator(test_runner, granularity, bugged_type, num_instances, tests_per_instance, bug_passing_probability)
  File "C:/Users/amirelm/Documents/GitHub/Debugger/learner\experiments.py", line 23, in __init__
    test_runner.get_tests())
  File "C:/Users/amirelm/Documents/GitHub/Debugger/learner\experiments.py", line 96, in get_components_probabilities
    components_priors[component] = max(float(predictions[sorted_list[index][::-1]]), 0.01)
KeyError: 'org.apache.flink.hadoop.shaded.com.google.common.collect.iterators'

**Comment by DebuggerIssuesReport** [comment]
Configuration is : 
('MethodsParsed', u'\\\\?\\C:\\amirelm\\projects\\FLINK_8\\repo\\commitsFiles\\CheckStyle.txt')
('full_configure_file', 'workingDir=C:\\amirelm\\projects\\FLINK_8\ngit=C:\\Temp\\apache_repos\\flink\nissue_tracker_product_name=FLINK\nissue_tracker_url=https://issues.apache.org/jira\nissue_tracker=jira\nvers=(release-1.1.3,release-1.1.4, release-1.2.0, release-1.1.5,release-1.3.2-rc3)\n')
('docletPath', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\xml-doclet-1.0.4-jar-with-dependencies.jar')
('experiments', u'C:\\amirelm\\projects\\FLINK_8\\experiments')
('sourceMonitorEXE', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\SourceMonitor.exe')
('checkStyle57', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\checkstyle-5.7-all.jar')
('gitPath', u'\\\\?\\C:\\Temp\\apache_repos\\flink')
('prediction_files', {'files': {'most': 'prediction_Most_files.csv', 'all': 'prediction_All_files.csv'}, 'methods': {'most': 'prediction_Most_methods.csv', 'all': 'prediction_All_methods.csv'}})
('debugger_base_path', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger')
('paths', ['release-1.1.3\\repo', 'release-1.1.4\\repo', 'release-1.2.0\\repo', 'release-1.1.5\\repo', 'release-1.3.2-rc3\\repo'])
('versPath', u'\\\\?\\C:\\amirelm\\projects\\FLINK_8\\vers')
('markers_dir', u'\\\\?\\C:\\amirelm\\projects\\FLINK_8\\markers')
('workingDir', u'\\\\?\\C:\\amirelm\\projects\\FLINK_8')
('RemoveBat', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\../removeBat.bat')
('caching_dir', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\Debugger_cache')
('issue_tracker_product', 'FLINK')
('db_dir', u'\\\\?\\C:\\amirelm\\projects\\FLINK_8\\dbAdd')
('LocalGitPath', u'\\\\?\\C:\\amirelm\\projects\\FLINK_8\\repo')
('changeFile', u'\\\\?\\C:\\amirelm\\projects\\FLINK_8\\repo\\commitsFiles\\Ins_dels.txt')
('vers', ['release-1.1.3', 'release-1.1.4', 'release-1.2.0', 'release-1.1.5', 'release-1.3.2-rc3'])
('utilsPath', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils')
('checkStyle68', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\checkstyle-6.8-SNAPSHOT-all.jar')
('commits', [149476436, 150671304, 248614551, 29776335, 3775470])
('methodsNamesXML', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\methodNameLines.xml')
('vers_dirs', ['release_1_1_3', 'release_1_1_4', 'release_1_2_0', 'release_1_1_5', 'release_1_3_2_rc3'])
('configuration_path', u'C:\\amirelm\\projects\\FLINK_8\\configuration')
('amir_tracer', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\uber-tracer-1.0.1-SNAPSHOT.jar')
('weka_path', u'C:\\amirelm\\projects\\FLINK_8\\weka')
('vers_paths', [u'\\\\?\\C:\\amirelm\\projects\\FLINK_8\\vers\\release_1_1_3', u'\\\\?\\C:\\amirelm\\projects\\FLINK_8\\vers\\release_1_1_4', u'\\\\?\\C:\\amirelm\\projects\\FLINK_8\\vers\\release_1_2_0', u'\\\\?\\C:\\amirelm\\projects\\FLINK_8\\vers\\release_1_1_5', u'\\\\?\\C:\\amirelm\\projects\\FLINK_8\\vers\\release_1_3_2_rc3'])
('bugsPath', u'\\\\?\\C:\\amirelm\\projects\\FLINK_8\\bugs.csv')
('issue_tracker', 'jira')
('dates', ['2016-10-10 16:26:32', '2016-12-19 12:42:50', '2017-03-17 12:54:11', '2017-01-29 23:19:15', '2017-08-03 13:23:11'])
('versions', ['release-1.1.3', 'release-1.1.4', 'release-1.2.0', 'release-1.1.5', 'release-1.3.2-rc3'])
('wekaJar', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\weka.jar')
('DebuggerTests', u'C:\\amirelm\\projects\\FLINK_8\\DebuggerTests')
('issue_tracker_url', 'https://issues.apache.org/jira')
('web_prediction_results', u'C:\\amirelm\\projects\\FLINK_8\\web_prediction_results')
('allchecks', 'C:\\Users\\amirelm\\Documents\\GitHub\\Debugger\\utils\\allChecks.xml')

**Comment by DebuggerIssuesReport** [comment]
DEBUG:git.util:Failed checking if running in CYGWIN due to: WindowsError(2, 'The system cannot find the file specified')
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=\\?\C:\Temp\apache_repos\flink, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch'], cwd=\\?\C:\Temp\apache_repos\flink, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=C:\Users\amirelm\Documents\GitHub\Debugger, universal_newlines=False, shell=None)
INFO:root:Debugger HEAD is on commit e8715dd6828e905e27d1b82f993bca70af0ec0c9
DEBUG:git.cmd:Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=\\?\C:\Temp\apache_repos\flink, universal_newlines=False, shell=None)
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_1_3\repo clean -fd release-1.1.3
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_1_3\repo checkout -f release-1.1.3
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_1_3\repo clean -fd release-1.1.3
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_1_4\repo clean -fd release-1.1.4
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_1_4\repo checkout -f release-1.1.4
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_1_4\repo clean -fd release-1.1.4
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_2_0\repo clean -fd release-1.2.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_2_0\repo checkout -f release-1.2.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_2_0\repo clean -fd release-1.2.0
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_1_5\repo clean -fd release-1.1.5
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_1_5\repo checkout -f release-1.1.5
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_1_5\repo clean -fd release-1.1.5
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_3_2_rc3\repo clean -fd release-1.3.2-rc3
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_3_2_rc3\repo checkout -f release-1.3.2-rc3
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\FLINK_8\vers\release_1_3_2_rc3\repo clean -fd release-1.3.2-rc3
INFO:root:running new process with cmdline git clone C:\Temp\apache_repos\flink repo
INFO:root:writing to \\?\C:\amirelm\projects\FLINK_8\markers\all_done: start time: 2018-09-02 20:07:30.204000

ERROR:root:error msg : org.apache.flink.hadoop.shaded.com.google.common.collect.iterators
Traceback (most recent call last):
  File "C:/Users/amirelm/Documents/GitHub/Debugger/learner\utilsConf.py", line 311, in f
    ans = func(*args, **kwargs)
  File "C:/Users/amirelm/Documents/GitHub/Debugger/learner/wrapper.py", line 538, in wrapperAll
    create_experiment(executeTests())
  File "C:/Users/amirelm/Documents/GitHub/Debugger/learner/wrapper.py", line 529, in create_experiment
    eg = ExperimentGenerator(test_runner, granularity, bugged_type, num_instances, tests_per_instance, bug_passing_probability)
  File "C:/Users/amirelm/Documents/GitHub/Debugger/learner\experiments.py", line 23, in __init__
    test_runner.get_tests())
  File "C:/Users/amirelm/Documents/GitHub/Debugger/learner\experiments.py", line 96, in get_components_probabilities
    components_priors[component] = max(float(predictions[sorted_list[index][::-1]]), 0.01)
KeyError: 'org.apache.flink.hadoop.shaded.com.google.common.collect.iterators'
INFO:github3:Building a url from ('https://api.github.com', 'repos', 'amir9979', 'Debugger')
INFO:github3:Missed the cache building the url
DEBUG:github3:GET https://api.github.com/repos/amir9979/Debugger with {}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/amir9979/Debugger HTTP/1.1" 200 None
INFO:github3:Attempting to get JSON information from a Response with status code 200 expecting 200
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/amir9979/Debugger', 'issues')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/amir9979/Debugger/issues with {"body": "An Exception occurred while running Debugger:\n\ncommand line is C:/Users/amirelm/Documents/GitHub/Debugger/learner/wrapper.py C:\\Users\\amirelm\\Documents\\GitHub\\repository_mining\\repository_data\\configurations\\FLINK_8\n\nTraceback (most recent call last):\n  File \"C:/Users/amirelm/Documents/GitHub/Debugger/learner\\utilsConf.py\", line 311, in f\n    ans = func(*args, **kwargs)\n  File \"C:/Users/amirelm/Documents/GitHub/Debugger/learner/wrapper.py\", line 538, in wrapperAll\n    create_experiment(executeTests())\n  File \"C:/Users/amirelm/Documents/GitHub/Debugger/learner/wrapper.py\", line 529, in create_experiment\n    eg = ExperimentGenerator(test_runner, granularity, bugged_type, num_instances, tests_per_instance, bug_passing_probability)\n  File \"C:/Users/amirelm/Documents/GitHub/Debugger/learner\\experiments.py\", line 23, in __init__\n    test_runner.get_tests())\n  File \"C:/Users/amirelm/Documents/GitHub/Debugger/learner\\experiments.py\", line 96, in get_components_probabilities\n    components_priors[component] = max(float(predictions[sorted_list[index][::-1]]), 0.01)\nKeyError: 'org.apache.flink.hadoop.shaded.com.google.common.collect.iterators'\n", "assignee": "amir9979", "title": "An Exception occurred : org.apache.flink.hadoop.shaded.com.google.common.collect.iterators"}, {}
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/amir9979/Debugger/issues HTTP/1.1" 201 5514
INFO:github3:Attempting to get JSON information from a Response with status code 201 expecting 201
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/amir9979/Debugger/issues/467', 'comments')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/amir9979/Debugger/issues/467/comments with {"body": "Configuration is : \n('MethodsParsed', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\repo\\\\commitsFiles\\\\CheckStyle.txt')\n('full_configure_file', 'workingDir=C:\\\\amirelm\\\\projects\\\\FLINK_8\\ngit=C:\\\\Temp\\\\apache_repos\\\\flink\\nissue_tracker_product_name=FLINK\\nissue_tracker_url=https://issues.apache.org/jira\\nissue_tracker=jira\\nvers=(release-1.1.3,release-1.1.4, release-1.2.0, release-1.1.5,release-1.3.2-rc3)\\n')\n('docletPath', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\xml-doclet-1.0.4-jar-with-dependencies.jar')\n('experiments', u'C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\experiments')\n('sourceMonitorEXE', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\SourceMonitor.exe')\n('checkStyle57', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\checkstyle-5.7-all.jar')\n('gitPath', u'\\\\\\\\?\\\\C:\\\\Temp\\\\apache_repos\\\\flink')\n('prediction_files', {'files': {'most': 'prediction_Most_files.csv', 'all': 'prediction_All_files.csv'}, 'methods': {'most': 'prediction_Most_methods.csv', 'all': 'prediction_All_methods.csv'}})\n('debugger_base_path', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger')\n('paths', ['release-1.1.3\\\\repo', 'release-1.1.4\\\\repo', 'release-1.2.0\\\\repo', 'release-1.1.5\\\\repo', 'release-1.3.2-rc3\\\\repo'])\n('versPath', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\vers')\n('markers_dir', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\markers')\n('workingDir', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\FLINK_8')\n('RemoveBat', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\../removeBat.bat')\n('caching_dir', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\Debugger_cache')\n('issue_tracker_product', 'FLINK')\n('db_dir', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\dbAdd')\n('LocalGitPath', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\repo')\n('changeFile', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\repo\\\\commitsFiles\\\\Ins_dels.txt')\n('vers', ['release-1.1.3', 'release-1.1.4', 'release-1.2.0', 'release-1.1.5', 'release-1.3.2-rc3'])\n('utilsPath', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils')\n('checkStyle68', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\checkstyle-6.8-SNAPSHOT-all.jar')\n('commits', [149476436, 150671304, 248614551, 29776335, 3775470])\n('methodsNamesXML', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\methodNameLines.xml')\n('vers_dirs', ['release_1_1_3', 'release_1_1_4', 'release_1_2_0', 'release_1_1_5', 'release_1_3_2_rc3'])\n('configuration_path', u'C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\configuration')\n('amir_tracer', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\uber-tracer-1.0.1-SNAPSHOT.jar')\n('weka_path', u'C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\weka')\n('vers_paths', [u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\vers\\\\release_1_1_3', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\vers\\\\release_1_1_4', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\vers\\\\release_1_2_0', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\vers\\\\release_1_1_5', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\vers\\\\release_1_3_2_rc3'])\n('bugsPath', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\bugs.csv')\n('issue_tracker', 'jira')\n('dates', ['2016-10-10 16:26:32', '2016-12-19 12:42:50', '2017-03-17 12:54:11', '2017-01-29 23:19:15', '2017-08-03 13:23:11'])\n('versions', ['release-1.1.3', 'release-1.1.4', 'release-1.2.0', 'release-1.1.5', 'release-1.3.2-rc3'])\n('wekaJar', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\weka.jar')\n('DebuggerTests', u'C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\DebuggerTests')\n('issue_tracker_url', 'https://issues.apache.org/jira')\n('web_prediction_results', u'C:\\\\amirelm\\\\projects\\\\FLINK_8\\\\web_prediction_results')\n('allchecks', 'C:\\\\Users\\\\amirelm\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\allChecks.xml')"}, {}
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/amir9979/Debugger/issues/467/comments HTTP/1.1" 201 13414
INFO:github3:Attempting to get JSON information from a Response with status code 201 expecting 201
INFO:github3:JSON was returned
