### ISSUE TITLE
An Exception occurred : 'Configuration' object has no attribute 'changeFilex'

### ISSUE THREAD

**Issue by DebuggerIssuesReport** [BGU-AiDnD/Debugger#640]
An Exception occurred while running Debugger:

command line is C:/Users/User/Documents/GitHub/Debugger/learner/wrapper.py C:\Users\User\Downloads\79f7a7ef529ae656a80f7e331f75e79999cef7ea.txt

Traceback (most recent call last):
  File "C:/Users/User/Documents/GitHub/Debugger/learner\utilsConf.py", line 364, in f
    ans = func(*args, **kwargs)
  File "C:/Users/User/Documents/GitHub/Debugger/learner\wekaMethods\patchsBuild.py", line 227, in labeling
    buildPatchs(patchD, commitsFiles, utilsConf.get_configuration().changeFilex)
AttributeError: 'Configuration' object has no attribute 'changeFilex'

**Comment by DebuggerIssuesReport** [comment]
Configuration is : 
('MethodsParsed', u'\\\\?\\C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\commitsFiles\\CheckStyle.txt')
('full_configure_file', 'workingDir=C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\ngit=C:\\Temp\\commons-lang\nissue_tracker_product_name=LANG\nissue_tracker_url=https://issues.apache.org/jira\nissue_tracker=jira\nvers=(LANG_2_5_RC1,LANG_2_5,LANG_2_5_RC3,LANG_3_0_B1,LANG_3_0_B2)')
('docletPath', 'C:\\Users\\User\\Documents\\GitHub\\Debugger\\utils\\xml-doclet-1.0.4-jar-with-dependencies.jar')
('experiments', u'C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\experiments')
('sourceMonitorEXE', 'C:\\Users\\User\\Documents\\GitHub\\Debugger\\utils\\SourceMonitor.exe')
('checkStyle57', 'C:\\Users\\User\\Documents\\GitHub\\Debugger\\utils\\checkstyle-5.7-all.jar')
('gitPath', u'\\\\?\\C:\\Temp\\commons-lang')
('prediction_files', {'files': {'most': 'prediction_Most_files.csv', 'all': 'prediction_All_files.csv'}, 'methods': {'most': 'prediction_Most_methods.csv', 'all': 'prediction_All_methods.csv'}})
('current_dir', 'C:\\Users\\User\\Documents\\GitHub\\Debugger\\learner')
('debugger_base_path', 'C:\\Users\\User\\Documents\\GitHub\\Debugger')
('paths', ['LANG_2_5_RC1\\repo', 'LANG_2_5\\repo', 'LANG_2_5_RC3\\repo', 'LANG_3_0_B1\\repo', 'LANG_3_0_B2\\repo'])
('versPath', u'\\\\?\\C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\vers')
('buggy_repo', <git.Repo "C:\Temp\commons-lang\.git">)
('markers_dir', u'\\\\?\\C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\markers')
('workingDir', u'\\\\?\\C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea')
('RemoveBat', 'C:\\Users\\User\\Documents\\GitHub\\Debugger\\utils\\../removeBat.bat')
('caching_dir', 'C:\\Users\\User\\Documents\\GitHub\\Debugger\\Debugger_cache')
('confFile', 'C:\\Users\\User\\Downloads\\79f7a7ef529ae656a80f7e331f75e79999cef7ea.txt')
('issue_tracker_product', 'LANG')
('db_dir', u'\\\\?\\C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\dbAdd')
('LocalGitPath', u'C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\repo')
('changeFile', u'\\\\?\\C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\commitsFiles\\Ins_dels.txt')
('vers', ['LANG_2_5_RC1', 'LANG_2_5', 'LANG_2_5_RC3', 'LANG_3_0_B1', 'LANG_3_0_B2'])
('utilsPath', 'C:\\Users\\User\\Documents\\GitHub\\Debugger\\utils')
('checkStyle68', 'C:\\Users\\User\\Documents\\GitHub\\Debugger\\utils\\checkstyle-6.8-SNAPSHOT-all.jar')
('commits', [130300012, 159637519, 8426563, 12204984, 262096358])
('methodsNamesXML', 'C:\\Users\\User\\Documents\\GitHub\\Debugger\\utils\\methodNameLines.xml')
('vers_dirs', ['LANG_2_5_RC1', 'LANG_2_5', 'LANG_2_5_RC3', 'LANG_3_0_B1', 'LANG_3_0_B2'])
('configuration_path', u'C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\configuration')
('amir_tracer', 'C:\\Users\\User\\Documents\\GitHub\\Debugger\\utils\\uber-tracer-1.0.1-SNAPSHOT.jar')
('distribution_report', u'\\\\?\\C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\distribution_report.csv')
('weka_path', u'C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\weka')
('vers_paths', [u'\\\\?\\C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\vers\\LANG_2_5_RC1', u'\\\\?\\C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\vers\\LANG_2_5', u'\\\\?\\C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\vers\\LANG_2_5_RC3', u'\\\\?\\C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\vers\\LANG_3_0_B1', u'\\\\?\\C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\vers\\LANG_3_0_B2'])
('configuration', <utilsConf.Configuration object at 0x07477E70>)
('bugsPath', u'\\\\?\\C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\bugs.csv')
('issue_tracker', 'jira')
('remotes_urls', [u'https://github.com/apache/commons-lang.git'])
('repo', <git.Repo "C:\Users\User\Documents\GitHub\Debugger\.git">)
('dates', ['2010-04-07 19:03:21', '2010-02-20 00:09:01', '2010-02-22 01:33:28', '2010-07-21 02:31:04', '2010-07-23 22:10:19'])
('renamed_mapping', {})
('versions', ['LANG_2_5_RC1', 'LANG_2_5', 'LANG_2_5_RC3', 'LANG_3_0_B1', 'LANG_3_0_B2'])
('wekaJar', 'C:\\Users\\User\\Documents\\GitHub\\Debugger\\utils\\weka.jar')
('DebuggerTests', u'C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\DebuggerTests')
('issue_tracker_url', 'https://issues.apache.org/jira')
('web_prediction_results', u'C:\\Temp\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\web_prediction_results')
('allchecks', 'C:\\Users\\User\\Documents\\GitHub\\Debugger\\utils\\allChecks.xml')

**Comment by DebuggerIssuesReport** [comment]
DEBUG:git.util:Failed checking if running in CYGWIN due to: WindowsError(2, 'The system cannot find the file specified')
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=C:\Temp\commons-lang, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch'], cwd=C:\Temp\commons-lang, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=C:\Temp\commons-lang, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=C:\Temp\commons-lang, universal_newlines=False, shell=None)
INFO:root:remote git at urls [u'https://github.com/apache/commons-lang.git'] and HEAD is on commit 69e843890c09861a168c6fe77d63fc72f0c73195
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=C:\Users\User\Documents\GitHub\Debugger, universal_newlines=False, shell=None)
INFO:root:Debugger HEAD is on commit ea8f16059ff17cd1ec8484978d755d12b6396f2d
INFO:root:writing to \\?\C:\Temp\79f7a7ef529ae656a80f7e331f75e79999cef7ea\markers\issue_tracker_file: start time: 2018-09-28 01:41:29.747000

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/serverInfo HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/field HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=0&maxResults=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=100&maxResults=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=200&maxResults=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=300&maxResults=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=400&maxResults=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=500&maxResults=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=600&maxResults=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=700&maxResults=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=800&maxResults=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=900&maxResults=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=1000&maxResults=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=1100&maxResults=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=1200&maxResults=100 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: issues.apache.org
DEBUG:urllib3.connectionpool:https://issues.apache.org:443 "GET /jira/rest/api/2/search?jql=project%3DLANG&validateQuery=True&startAt=1300&maxResults=100 HTTP/1.1" 200 None
INFO:root:writing to \\?\C:\Temp\79f7a7ef529ae656a80f7e331f75e79999cef7ea\markers\issue_tracker_file: finish time: 2018-09-28 01:42:13.804000

INFO:root:running new process with cmdline git clone C:\Temp\commons-lang repo
INFO:root:writing to \\?\C:\Temp\79f7a7ef529ae656a80f7e331f75e79999cef7ea\markers\distribution_file: start time: 2018-09-28 01:42:15.079000

INFO:root:writing to \\?\C:\Temp\79f7a7ef529ae656a80f7e331f75e79999cef7ea\markers\patchs_features: start time: 2018-09-28 01:42:15.080000

INFO:root:running new process with cmdline git format-patch --root -o ..\patch --function-context --unified=900000
ERROR:root:error msg : 'Configuration' object has no attribute 'changeFilex'
Traceback (most recent call last):
  File "C:/Users/User/Documents/GitHub/Debugger/learner\utilsConf.py", line 364, in f
    ans = func(*args, **kwargs)
  File "C:/Users/User/Documents/GitHub/Debugger/learner\wekaMethods\patchsBuild.py", line 227, in labeling
    buildPatchs(patchD, commitsFiles, utilsConf.get_configuration().changeFilex)
AttributeError: 'Configuration' object has no attribute 'changeFilex'
INFO:github3:Building a url from ('https://api.github.com', 'repos', 'amir9979', 'Debugger')
INFO:github3:Missed the cache building the url
DEBUG:github3:GET https://api.github.com/repos/amir9979/Debugger with {}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/amir9979/Debugger HTTP/1.1" 200 None
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/amir9979/Debugger', 'issues')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/amir9979/Debugger/issues with {"body": "An Exception occurred while running Debugger:\n\ncommand line is C:/Users/User/Documents/GitHub/Debugger/learner/wrapper.py C:\\Users\\User\\Downloads\\79f7a7ef529ae656a80f7e331f75e79999cef7ea.txt\n\nTraceback (most recent call last):\n  File \"C:/Users/User/Documents/GitHub/Debugger/learner\\utilsConf.py\", line 364, in f\n    ans = func(*args, **kwargs)\n  File \"C:/Users/User/Documents/GitHub/Debugger/learner\\wekaMethods\\patchsBuild.py\", line 227, in labeling\n    buildPatchs(patchD, commitsFiles, utilsConf.get_configuration().changeFilex)\nAttributeError: 'Configuration' object has no attribute 'changeFilex'\n", "assignee": "amir9979", "title": "An Exception occurred : 'Configuration' object has no attribute 'changeFilex'"}, {}
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/amir9979/Debugger/issues HTTP/1.1" 201 3812
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/amir9979/Debugger/issues/640', 'comments')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/amir9979/Debugger/issues/640/comments with {"body": "Configuration is : \n('MethodsParsed', u'\\\\\\\\?\\\\C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\commitsFiles\\\\CheckStyle.txt')\n('full_configure_file', 'workingDir=C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\ngit=C:\\\\Temp\\\\commons-lang\\nissue_tracker_product_name=LANG\\nissue_tracker_url=https://issues.apache.org/jira\\nissue_tracker=jira\\nvers=(LANG_2_5_RC1,LANG_2_5,LANG_2_5_RC3,LANG_3_0_B1,LANG_3_0_B2)')\n('docletPath', 'C:\\\\Users\\\\User\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\xml-doclet-1.0.4-jar-with-dependencies.jar')\n('experiments', u'C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\experiments')\n('sourceMonitorEXE', 'C:\\\\Users\\\\User\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\SourceMonitor.exe')\n('checkStyle57', 'C:\\\\Users\\\\User\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\checkstyle-5.7-all.jar')\n('gitPath', u'\\\\\\\\?\\\\C:\\\\Temp\\\\commons-lang')\n('prediction_files', {'files': {'most': 'prediction_Most_files.csv', 'all': 'prediction_All_files.csv'}, 'methods': {'most': 'prediction_Most_methods.csv', 'all': 'prediction_All_methods.csv'}})\n('current_dir', 'C:\\\\Users\\\\User\\\\Documents\\\\GitHub\\\\Debugger\\\\learner')\n('debugger_base_path', 'C:\\\\Users\\\\User\\\\Documents\\\\GitHub\\\\Debugger')\n('paths', ['LANG_2_5_RC1\\\\repo', 'LANG_2_5\\\\repo', 'LANG_2_5_RC3\\\\repo', 'LANG_3_0_B1\\\\repo', 'LANG_3_0_B2\\\\repo'])\n('versPath', u'\\\\\\\\?\\\\C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\vers')\n('buggy_repo', <git.Repo \"C:\\Temp\\commons-lang\\.git\">)\n('markers_dir', u'\\\\\\\\?\\\\C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\markers')\n('workingDir', u'\\\\\\\\?\\\\C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea')\n('RemoveBat', 'C:\\\\Users\\\\User\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\../removeBat.bat')\n('caching_dir', 'C:\\\\Users\\\\User\\\\Documents\\\\GitHub\\\\Debugger\\\\Debugger_cache')\n('confFile', 'C:\\\\Users\\\\User\\\\Downloads\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea.txt')\n('issue_tracker_product', 'LANG')\n('db_dir', u'\\\\\\\\?\\\\C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\dbAdd')\n('LocalGitPath', u'C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\repo')\n('changeFile', u'\\\\\\\\?\\\\C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\commitsFiles\\\\Ins_dels.txt')\n('vers', ['LANG_2_5_RC1', 'LANG_2_5', 'LANG_2_5_RC3', 'LANG_3_0_B1', 'LANG_3_0_B2'])\n('utilsPath', 'C:\\\\Users\\\\User\\\\Documents\\\\GitHub\\\\Debugger\\\\utils')\n('checkStyle68', 'C:\\\\Users\\\\User\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\checkstyle-6.8-SNAPSHOT-all.jar')\n('commits', [130300012, 159637519, 8426563, 12204984, 262096358])\n('methodsNamesXML', 'C:\\\\Users\\\\User\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\methodNameLines.xml')\n('vers_dirs', ['LANG_2_5_RC1', 'LANG_2_5', 'LANG_2_5_RC3', 'LANG_3_0_B1', 'LANG_3_0_B2'])\n('configuration_path', u'C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\configuration')\n('amir_tracer', 'C:\\\\Users\\\\User\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\uber-tracer-1.0.1-SNAPSHOT.jar')\n('distribution_report', u'\\\\\\\\?\\\\C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\distribution_report.csv')\n('weka_path', u'C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\weka')\n('vers_paths', [u'\\\\\\\\?\\\\C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\vers\\\\LANG_2_5_RC1', u'\\\\\\\\?\\\\C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\vers\\\\LANG_2_5', u'\\\\\\\\?\\\\C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\vers\\\\LANG_2_5_RC3', u'\\\\\\\\?\\\\C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\vers\\\\LANG_3_0_B1', u'\\\\\\\\?\\\\C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\vers\\\\LANG_3_0_B2'])\n('configuration', <utilsConf.Configuration object at 0x07477E70>)\n('bugsPath', u'\\\\\\\\?\\\\C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\bugs.csv')\n('issue_tracker', 'jira')\n('remotes_urls', [u'https://github.com/apache/commons-lang.git'])\n('repo', <git.Repo \"C:\\Users\\User\\Documents\\GitHub\\Debugger\\.git\">)\n('dates', ['2010-04-07 19:03:21', '2010-02-20 00:09:01', '2010-02-22 01:33:28', '2010-07-21 02:31:04', '2010-07-23 22:10:19'])\n('renamed_mapping', {})\n('versions', ['LANG_2_5_RC1', 'LANG_2_5', 'LANG_2_5_RC3', 'LANG_3_0_B1', 'LANG_3_0_B2'])\n('wekaJar', 'C:\\\\Users\\\\User\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\weka.jar')\n('DebuggerTests', u'C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\DebuggerTests')\n('issue_tracker_url', 'https://issues.apache.org/jira')\n('web_prediction_results', u'C:\\\\Temp\\\\79f7a7ef529ae656a80f7e331f75e79999cef7ea\\\\web_prediction_results')\n('allchecks', 'C:\\\\Users\\\\User\\\\Documents\\\\GitHub\\\\Debugger\\\\utils\\\\allChecks.xml')"}, {}
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/amir9979/Debugger/issues/640/comments HTTP/1.1" 201 15829
INFO:github3:JSON was returned
