### ISSUE TITLE
An Exception occurred : unhashable type: 'list'

### ISSUE THREAD

**Issue by DebuggerIssuesReport** [BGU-AiDnD/Debugger#660]
An Exception occurred while running Debugger:

command line is C:/Users/inbalros/PycharmProjects/Debugger/learner/wrapper.py C:\temp\run_configuration

Traceback (most recent call last):
  File "C:/Users/inbalros/PycharmProjects/Debugger/learner\utilsConf.py", line 320, in f
    ans = func(*args, **kwargs)
  File "C:/Users/inbalros/PycharmProjects/Debugger/learner/wrapper.py", line 374, in run_mvn_on_vers
    TestRunner(os.path.join(version, 'repo')).run()
  File "C:/Users/inbalros/PycharmProjects/Debugger/learner\run_mvn.py", line 159, in __init__
    self.java_path = get_java_path_version(self.get_java_versions())
  File "C:/Users/inbalros/PycharmProjects/Debugger/learner\run_mvn.py", line 170, in get_java_versions
    java_versions.add(PomReader.get_children_by_name(configuration, 'source'))
TypeError: unhashable type: 'list'

**Comment by DebuggerIssuesReport** [comment]
Configuration is : 
('MethodsParsed', u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run\\repo\\commitsFiles\\CheckStyle.txt')
('full_configure_file', 'workingDir=C:\\amirelm\\projects\\CAY_5_run\ngit=C:\\Temp\\apache_repos\\cayenne\nissue_tracker_product_name=CAY\nissue_tracker_url=https://issues.apache.org/jira\nissue_tracker=jira\nvers=(3.1M1,3.1M2, 3.0.2, 3.1M3,3.1B1)\n')
('docletPath', 'C:\\Users\\inbalros\\PycharmProjects\\Debugger\\utils\\xml-doclet-1.0.4-jar-with-dependencies.jar')
('experiments', u'C:\\amirelm\\projects\\CAY_5_run\\experiments')
('sourceMonitorEXE', 'C:\\Users\\inbalros\\PycharmProjects\\Debugger\\utils\\SourceMonitor.exe')
('checkStyle57', 'C:\\Users\\inbalros\\PycharmProjects\\Debugger\\utils\\checkstyle-5.7-all.jar')
('gitPath', u'\\\\?\\C:\\Temp\\apache_repos\\cayenne')
('prediction_files', {'files': {'most': 'prediction_Most_files.csv', 'all': 'prediction_All_files.csv'}, 'methods': {'most': 'prediction_Most_methods.csv', 'all': 'prediction_All_methods.csv'}})
('current_dir', 'C:\\Users\\inbalros\\PycharmProjects\\Debugger\\learner')
('debugger_base_path', 'C:\\Users\\inbalros\\PycharmProjects\\Debugger')
('paths', ['3.1M1\\repo', '3.1M2\\repo', '3.0.2\\repo', '3.1M3\\repo', '3.1B1\\repo'])
('versPath', u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run\\vers')
('markers_dir', u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run\\markers')
('workingDir', u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run')
('RemoveBat', 'C:\\Users\\inbalros\\PycharmProjects\\Debugger\\utils\\../removeBat.bat')
('caching_dir', 'C:\\Users\\inbalros\\PycharmProjects\\Debugger\\Debugger_cache')
('confFile', 'C:\\temp\\run_configuration')
('issue_tracker_product', 'CAY')
('db_dir', u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run\\dbAdd')
('LocalGitPath', u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run\\repo')
('changeFile', u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run\\repo\\commitsFiles\\Ins_dels.txt')
('vers', ['3.1M1', '3.1M2', '3.0.2', '3.1M3', '3.1B1'])
('utilsPath', 'C:\\Users\\inbalros\\PycharmProjects\\Debugger\\utils')
('checkStyle68', 'C:\\Users\\inbalros\\PycharmProjects\\Debugger\\utils\\checkstyle-6.8-SNAPSHOT-all.jar')
('commits', [67587298, 226550004, 67111501, 259779950, 25988596])
('methodsNamesXML', 'C:\\Users\\inbalros\\PycharmProjects\\Debugger\\utils\\methodNameLines.xml')
('vers_dirs', ['3_1M1', '3_1M2', '3_0_2', '3_1M3', '3_1B1'])
('configuration_path', u'C:\\amirelm\\projects\\CAY_5_run\\configuration')
('amir_tracer', 'C:\\Users\\inbalros\\PycharmProjects\\Debugger\\utils\\uber-tracer-1.0.1-SNAPSHOT.jar')
('repo', <git.Repo "\\?\C:\Temp\apache_repos\cayenne\.git">)
('weka_path', u'C:\\amirelm\\projects\\CAY_5_run\\weka')
('vers_paths', [u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run\\vers\\3_1M1', u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run\\vers\\3_1M2', u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run\\vers\\3_0_2', u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run\\vers\\3_1M3', u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run\\vers\\3_1B1'])
('configuration', <utilsConf.Configuration object at 0x000000000B6F97F0>)
('bugsPath', u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run\\bugs.csv')
('issue_tracker', 'jira')
('remotes_urls', [u'https://github.com/apache/cayenne.git'])
('dates', ['2011-06-11 11:41:04', '2012-05-28 20:32:48', '2010-11-14 09:17:15', '2011-02-21 10:55:55', '2011-09-26 10:00:59'])
('versions', ['3.1M1', '3.1M2', '3.0.2', '3.1M3', '3.1B1'])
('wekaJar', 'C:\\Users\\inbalros\\PycharmProjects\\Debugger\\utils\\weka.jar')
('DebuggerTests', u'C:\\amirelm\\projects\\CAY_5_run\\DebuggerTests')
('compiled_vers_paths', [u'C:\\amirelm\\projects\\CAY_5_run\\compiled_versions\\3_1M1', u'C:\\amirelm\\projects\\CAY_5_run\\compiled_versions\\3_1M2', u'C:\\amirelm\\projects\\CAY_5_run\\compiled_versions\\3_0_2', u'C:\\amirelm\\projects\\CAY_5_run\\compiled_versions\\3_1M3', u'C:\\amirelm\\projects\\CAY_5_run\\compiled_versions\\3_1B1'])
('issue_tracker_url', 'https://issues.apache.org/jira')
('compiled_versions', u'\\\\?\\C:\\amirelm\\projects\\CAY_5_run\\compiled_versions')
('web_prediction_results', u'C:\\amirelm\\projects\\CAY_5_run\\web_prediction_results')
('allchecks', 'C:\\Users\\inbalros\\PycharmProjects\\Debugger\\utils\\allChecks.xml')

**Comment by DebuggerIssuesReport** [comment]
DEBUG:git.util:Failed checking if running in CYGWIN due to: WindowsError(2, 'The system cannot find the file specified')
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=\\?\C:\Temp\apache_repos\cayenne, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch'], cwd=\\?\C:\Temp\apache_repos\cayenne, universal_newlines=False, shell=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=C:\Users\inbalros\PycharmProjects\Debugger, universal_newlines=False, shell=None)
INFO:root:Debugger HEAD is on commit a639faff777890e7b52cbf0589d5a2ea90f2961e
DEBUG:git.cmd:Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=\\?\C:\Temp\apache_repos\cayenne, universal_newlines=False, shell=None)
INFO:root:running new process with cmdline git clone C:\Temp\apache_repos\cayenne repo
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_1M1\repo clean -fd 3.1M1
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_1M1\repo checkout -f 3.1M1
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_1M1\repo clean -fd 3.1M1
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_1M2\repo clean -fd 3.1M2
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_1M2\repo checkout -f 3.1M2
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_1M2\repo clean -fd 3.1M2
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_0_2\repo clean -fd 3.0.2
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_0_2\repo checkout -f 3.0.2
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_0_2\repo clean -fd 3.0.2
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_1M3\repo clean -fd 3.1M3
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_1M3\repo checkout -f 3.1M3
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_1M3\repo clean -fd 3.1M3
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_1B1\repo clean -fd 3.1B1
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_1B1\repo checkout -f 3.1B1
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\vers\3_1B1\repo clean -fd 3.1B1
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_1M1\repo clean -fd 3.1M1
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_1M1\repo checkout -f 3.1M1
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_1M1\repo clean -fd 3.1M1
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_1M2\repo clean -fd 3.1M2
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_1M2\repo checkout -f 3.1M2
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_1M2\repo clean -fd 3.1M2
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_0_2\repo clean -fd 3.0.2
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_0_2\repo checkout -f 3.0.2
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_0_2\repo clean -fd 3.0.2
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_1M3\repo clean -fd 3.1M3
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_1M3\repo checkout -f 3.1M3
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_1M3\repo clean -fd 3.1M3
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_1B1\repo clean -fd 3.1B1
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_1B1\repo checkout -f 3.1B1
INFO:root:running new process with cmdline git -C \\?\C:\amirelm\projects\CAY_5_run\compiled_versions\3_1B1\repo clean -fd 3.1B1
INFO:root:writing to \\?\C:\amirelm\projects\CAY_5_run\markers\dynamic_run_file: start time: 2018-09-28 16:27:46.630000

ERROR:root:error msg : unhashable type: 'list'
Traceback (most recent call last):
  File "C:/Users/inbalros/PycharmProjects/Debugger/learner\utilsConf.py", line 320, in f
    ans = func(*args, **kwargs)
  File "C:/Users/inbalros/PycharmProjects/Debugger/learner/wrapper.py", line 374, in run_mvn_on_vers
    TestRunner(os.path.join(version, 'repo')).run()
  File "C:/Users/inbalros/PycharmProjects/Debugger/learner\run_mvn.py", line 159, in __init__
    self.java_path = get_java_path_version(self.get_java_versions())
  File "C:/Users/inbalros/PycharmProjects/Debugger/learner\run_mvn.py", line 170, in get_java_versions
    java_versions.add(PomReader.get_children_by_name(configuration, 'source'))
TypeError: unhashable type: 'list'
INFO:github3:Building a url from ('https://api.github.com', 'repos', 'amir9979', 'Debugger')
INFO:github3:Missed the cache building the url
DEBUG:github3:GET https://api.github.com/repos/amir9979/Debugger with {}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/amir9979/Debugger HTTP/1.1" 200 None
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/amir9979/Debugger', 'issues')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/amir9979/Debugger/issues with {"body": "An Exception occurred while running Debugger:\n\ncommand line is C:/Users/inbalros/PycharmProjects/Debugger/learner/wrapper.py C:\\temp\\run_configuration\n\nTraceback (most recent call last):\n  File \"C:/Users/inbalros/PycharmProjects/Debugger/learner\\utilsConf.py\", line 320, in f\n    ans = func(*args, **kwargs)\n  File \"C:/Users/inbalros/PycharmProjects/Debugger/learner/wrapper.py\", line 374, in run_mvn_on_vers\n    TestRunner(os.path.join(version, 'repo')).run()\n  File \"C:/Users/inbalros/PycharmProjects/Debugger/learner\\run_mvn.py\", line 159, in __init__\n    self.java_path = get_java_path_version(self.get_java_versions())\n  File \"C:/Users/inbalros/PycharmProjects/Debugger/learner\\run_mvn.py\", line 170, in get_java_versions\n    java_versions.add(PomReader.get_children_by_name(configuration, 'source'))\nTypeError: unhashable type: 'list'\n", "assignee": "amir9979", "title": "An Exception occurred : unhashable type: 'list'"}, {}
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/amir9979/Debugger/issues HTTP/1.1" 201 4515
INFO:github3:JSON was returned
INFO:github3:Building a url from ('https://api.github.com/repos/amir9979/Debugger/issues/660', 'comments')
INFO:github3:Missed the cache building the url
DEBUG:github3:POST https://api.github.com/repos/amir9979/Debugger/issues/660/comments with {"body": "Configuration is : \n('MethodsParsed', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\repo\\\\commitsFiles\\\\CheckStyle.txt')\n('full_configure_file', 'workingDir=C:\\\\amirelm\\\\projects\\\\CAY_5_run\\ngit=C:\\\\Temp\\\\apache_repos\\\\cayenne\\nissue_tracker_product_name=CAY\\nissue_tracker_url=https://issues.apache.org/jira\\nissue_tracker=jira\\nvers=(3.1M1,3.1M2, 3.0.2, 3.1M3,3.1B1)\\n')\n('docletPath', 'C:\\\\Users\\\\inbalros\\\\PycharmProjects\\\\Debugger\\\\utils\\\\xml-doclet-1.0.4-jar-with-dependencies.jar')\n('experiments', u'C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\experiments')\n('sourceMonitorEXE', 'C:\\\\Users\\\\inbalros\\\\PycharmProjects\\\\Debugger\\\\utils\\\\SourceMonitor.exe')\n('checkStyle57', 'C:\\\\Users\\\\inbalros\\\\PycharmProjects\\\\Debugger\\\\utils\\\\checkstyle-5.7-all.jar')\n('gitPath', u'\\\\\\\\?\\\\C:\\\\Temp\\\\apache_repos\\\\cayenne')\n('prediction_files', {'files': {'most': 'prediction_Most_files.csv', 'all': 'prediction_All_files.csv'}, 'methods': {'most': 'prediction_Most_methods.csv', 'all': 'prediction_All_methods.csv'}})\n('current_dir', 'C:\\\\Users\\\\inbalros\\\\PycharmProjects\\\\Debugger\\\\learner')\n('debugger_base_path', 'C:\\\\Users\\\\inbalros\\\\PycharmProjects\\\\Debugger')\n('paths', ['3.1M1\\\\repo', '3.1M2\\\\repo', '3.0.2\\\\repo', '3.1M3\\\\repo', '3.1B1\\\\repo'])\n('versPath', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\vers')\n('markers_dir', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\markers')\n('workingDir', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run')\n('RemoveBat', 'C:\\\\Users\\\\inbalros\\\\PycharmProjects\\\\Debugger\\\\utils\\\\../removeBat.bat')\n('caching_dir', 'C:\\\\Users\\\\inbalros\\\\PycharmProjects\\\\Debugger\\\\Debugger_cache')\n('confFile', 'C:\\\\temp\\\\run_configuration')\n('issue_tracker_product', 'CAY')\n('db_dir', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\dbAdd')\n('LocalGitPath', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\repo')\n('changeFile', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\repo\\\\commitsFiles\\\\Ins_dels.txt')\n('vers', ['3.1M1', '3.1M2', '3.0.2', '3.1M3', '3.1B1'])\n('utilsPath', 'C:\\\\Users\\\\inbalros\\\\PycharmProjects\\\\Debugger\\\\utils')\n('checkStyle68', 'C:\\\\Users\\\\inbalros\\\\PycharmProjects\\\\Debugger\\\\utils\\\\checkstyle-6.8-SNAPSHOT-all.jar')\n('commits', [67587298, 226550004, 67111501, 259779950, 25988596])\n('methodsNamesXML', 'C:\\\\Users\\\\inbalros\\\\PycharmProjects\\\\Debugger\\\\utils\\\\methodNameLines.xml')\n('vers_dirs', ['3_1M1', '3_1M2', '3_0_2', '3_1M3', '3_1B1'])\n('configuration_path', u'C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\configuration')\n('amir_tracer', 'C:\\\\Users\\\\inbalros\\\\PycharmProjects\\\\Debugger\\\\utils\\\\uber-tracer-1.0.1-SNAPSHOT.jar')\n('repo', <git.Repo \"\\\\?\\C:\\Temp\\apache_repos\\cayenne\\.git\">)\n('weka_path', u'C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\weka')\n('vers_paths', [u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\vers\\\\3_1M1', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\vers\\\\3_1M2', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\vers\\\\3_0_2', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\vers\\\\3_1M3', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\vers\\\\3_1B1'])\n('configuration', <utilsConf.Configuration object at 0x000000000B6F97F0>)\n('bugsPath', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\bugs.csv')\n('issue_tracker', 'jira')\n('remotes_urls', [u'https://github.com/apache/cayenne.git'])\n('dates', ['2011-06-11 11:41:04', '2012-05-28 20:32:48', '2010-11-14 09:17:15', '2011-02-21 10:55:55', '2011-09-26 10:00:59'])\n('versions', ['3.1M1', '3.1M2', '3.0.2', '3.1M3', '3.1B1'])\n('wekaJar', 'C:\\\\Users\\\\inbalros\\\\PycharmProjects\\\\Debugger\\\\utils\\\\weka.jar')\n('DebuggerTests', u'C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\DebuggerTests')\n('compiled_vers_paths', [u'C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\compiled_versions\\\\3_1M1', u'C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\compiled_versions\\\\3_1M2', u'C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\compiled_versions\\\\3_0_2', u'C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\compiled_versions\\\\3_1M3', u'C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\compiled_versions\\\\3_1B1'])\n('issue_tracker_url', 'https://issues.apache.org/jira')\n('compiled_versions', u'\\\\\\\\?\\\\C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\compiled_versions')\n('web_prediction_results', u'C:\\\\amirelm\\\\projects\\\\CAY_5_run\\\\web_prediction_results')\n('allchecks', 'C:\\\\Users\\\\inbalros\\\\PycharmProjects\\\\Debugger\\\\utils\\\\allChecks.xml')"}, {}
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/amir9979/Debugger/issues/660/comments HTTP/1.1" 201 15041
INFO:github3:JSON was returned
