### ISSUE TITLE
An Exception occurred : need more than 1 value to unpack

### ISSUE THREAD

**Issue by DebuggerIssuesReport** [BGU-AiDnD/Debugger#711]
An Exception occurred while running Debugger:

command line is C:\Users\eranhe\Fault_Predicition_Defect4J\repo\Debugger\learner\wrapper.py C:\Users\eranhe\Fault_Predicition_Defect4J\conf\Chart\conf_chart.txt learn

Traceback (most recent call last):
  File "C:\Users\eranhe\Fault_Predicition_Defect4J\repo\Debugger\learner\utilsConf.py", line 369, in f
    ans = func(*args, **kwargs)
  File "C:\Users\eranhe\Fault_Predicition_Defect4J\repo\Debugger\learner\wrapper.py", line 305, in check_distribution
    prev_date, start_date, end_date = dates[i: i + 3]
ValueError: need more than 1 value to unpack

**Comment by DebuggerIssuesReport** [comment]
Configuration is : 
('MethodsParsed', u'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\commitsFiles\\CheckStyle.txt')
('full_configure_file', 'workingDir=C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\ngit=C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\jfreechart\nissue_tracker_product_name=C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\num_of_bug_csv\\Linux_DATA\\Chart\\log_commits.csv\nissue_tracker_url=None\nissue_tracker=csv_file\nvers=(520a4be69ba932061ab9b89f328842caf152e1d9,b4da8ae1f16ed92650541539d9212fd316514941,6f8f85d378dbb27da3855892a1cee294e7154a3d)')
('docletPath', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\Debugger\\utils\\xml-doclet-1.0.4-jar-with-dependencies.jar')
('distribution_per_version_report', u'\\\\?\\C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\distribution_per_version_report.csv')
('experiments', u'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\experiments')
('sourceMonitorEXE', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\Debugger\\utils\\SourceMonitor.exe')
('checkStyle57', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\Debugger\\utils\\checkstyle-5.7-all.jar')
('gitPath', u'\\\\?\\C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\jfreechart')
('prediction_files', {'files': {'most': 'prediction_Most_files.csv', 'all': 'prediction_All_files.csv'}, 'methods': {'most': 'prediction_Most_methods.csv', 'all': 'prediction_All_methods.csv'}})
('current_dir', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\Debugger\\learner')
('debugger_base_path', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\Debugger')
('paths', ['520a4be69ba932061ab9b89f328842caf152e1d9\\repo', 'b4da8ae1f16ed92650541539d9212fd316514941\\repo', '6f8f85d378dbb27da3855892a1cee294e7154a3d\\repo'])
('versPath', u'\\\\?\\C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\vers')
('buggy_repo', <git.Repo "C:\Users\eranhe\Fault_Predicition_Defect4J\repo\jfreechart\.git">)
('markers_dir', u'\\\\?\\C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\markers')
('workingDir', u'\\\\?\\C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart')
('RemoveBat', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\Debugger\\utils\\../removeBat.bat')
('caching_dir', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\Debugger\\Debugger_cache')
('confFile', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\conf\\Chart\\conf_chart.txt')
('issue_tracker_product', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\num_of_bug_csv\\Linux_DATA\\Chart\\log_commits.csv')
('db_dir', u'\\\\?\\C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\dbAdd')
('LocalGitPath', u'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\repo')
('changeFile', u'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\commitsFiles\\Ins_dels.txt')
('vers', ['520a4be69ba932061ab9b89f328842caf152e1d9', 'b4da8ae1f16ed92650541539d9212fd316514941', '6f8f85d378dbb27da3855892a1cee294e7154a3d'])
('utilsPath', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\Debugger\\utils')
('checkStyle68', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\Debugger\\utils\\checkstyle-6.8-SNAPSHOT-all.jar')
('commits', [])
('methodsNamesXML', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\Debugger\\utils\\methodNameLines.xml')
('vers_dirs', ['520a4be69ba932061ab9b89f328842caf152e1d9', 'b4da8ae1f16ed92650541539d9212fd316514941', '6f8f85d378dbb27da3855892a1cee294e7154a3d'])
('configuration_path', u'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\configuration')
('amir_tracer', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\Debugger\\utils\\uber-tracer-1.0.1-SNAPSHOT.jar')
('distribution_report', u'\\\\?\\C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\distribution_report.csv')
('weka_path', u'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\weka')
('vers_paths', [u'\\\\?\\C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\vers\\520a4be69ba932061ab9b89f328842caf152e1d9', u'\\\\?\\C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\vers\\b4da8ae1f16ed92650541539d9212fd316514941', u'\\\\?\\C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\vers\\6f8f85d378dbb27da3855892a1cee294e7154a3d'])
('configuration', <utilsConf.Configuration object at 0x0000000007F87A58>)
('bugsPath', u'\\\\?\\C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\bugs.csv')
('issue_tracker', 'csv_file')
('remotes_urls', [u'https://github.com/jfree/jfreechart.git'])
('repo', <git.Repo "C:\Users\eranhe\Fault_Predicition_Defect4J\repo\Debugger\.git">)
('dates', [])
('renamed_mapping', {})
('versions', ['520a4be69ba932061ab9b89f328842caf152e1d9', 'b4da8ae1f16ed92650541539d9212fd316514941', '6f8f85d378dbb27da3855892a1cee294e7154a3d'])
('wekaJar', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\Debugger\\utils\\weka.jar')
('DebuggerTests', u'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\DebuggerTests')
('issue_tracker_url', 'None')
('debugger_commit', '92e583bae315dfff05b447d7e7fb346ee401177f')
('web_prediction_results', u'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\rss\\chart\\web_prediction_results')
('allchecks', 'C:\\Users\\eranhe\\Fault_Predicition_Defect4J\\repo\\Debugger\\utils\\allChecks.xml')
